/**
 * PDF Export Utilities
 * Generate professional PDF reports for compliance documentation
 */

export interface PDFReportConfig {
  title: string
  subtitle?: string
  organizationName: string
  generatedBy: string
  generatedAt: Date
  dateRange?: {
    from: Date
    to: Date
  }
  logo?: string
}

export interface PDFSection {
  heading: string
  content: string | string[] | Record<string, any>
  type?: 'text' | 'table' | 'chart' | 'list'
}

/**
 * Generate HTML for PDF conversion
 * Uses browser print CSS for professional formatting
 */
export function generateReportHTML(
  config: PDFReportConfig,
  sections: PDFSection[]
): string {
  const dateRangeText = config.dateRange 
    ? `${formatDate(config.dateRange.from)} - ${formatDate(config.dateRange.to)}`
    : formatDate(config.generatedAt)

  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${config.title}</title>
  <style>
    @page {
      size: A4;
      margin: 20mm;
    }
    
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    
    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      font-size: 11pt;
      line-height: 1.6;
      color: #333;
    }
    
    .header {
      border-bottom: 3px solid #2563eb;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    
    .header h1 {
      color: #1e40af;
      font-size: 24pt;
      margin-bottom: 5px;
    }
    
    .header .subtitle {
      color: #6b7280;
      font-size: 12pt;
      margin-bottom: 15px;
    }
    
    .header .meta {
      display: flex;
      justify-content: space-between;
      font-size: 9pt;
      color: #6b7280;
    }
    
    .section {
      margin-bottom: 25px;
      page-break-inside: avoid;
    }
    
    .section h2 {
      color: #1e40af;
      font-size: 14pt;
      border-bottom: 1px solid #e5e7eb;
      padding-bottom: 5px;
      margin-bottom: 15px;
    }
    
    .section p {
      margin-bottom: 10px;
    }
    
    table {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 15px;
    }
    
    th {
      background-color: #f3f4f6;
      border: 1px solid #d1d5db;
      padding: 8px;
      text-align: left;
      font-weight: 600;
      font-size: 10pt;
    }
    
    td {
      border: 1px solid #d1d5db;
      padding: 8px;
      font-size: 10pt;
    }
    
    tr:nth-child(even) {
      background-color: #f9fafb;
    }
    
    ul, ol {
      margin-left: 20px;
      margin-bottom: 10px;
    }
    
    li {
      margin-bottom: 5px;
    }
    
    .footer {
      margin-top: 50px;
      padding-top: 20px;
      border-top: 1px solid #e5e7eb;
      text-align: center;
      font-size: 9pt;
      color: #6b7280;
    }
    
    .badge {
      display: inline-block;
      padding: 2px 8px;
      border-radius: 4px;
      font-size: 9pt;
      font-weight: 600;
    }
    
    .badge-green {
      background-color: #d1fae5;
      color: #065f46;
    }
    
    .badge-red {
      background-color: #fee2e2;
      color: #991b1b;
    }
    
    .badge-orange {
      background-color: #fed7aa;
      color: #92400e;
    }
    
    @media print {
      body {
        print-color-adjust: exact;
        -webkit-print-color-adjust: exact;
      }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>${config.title}</h1>
    ${config.subtitle ? `<div class="subtitle">${config.subtitle}</div>` : ''}
    <div class="meta">
      <div>
        <strong>Organization:</strong> ${config.organizationName}<br>
        <strong>Generated by:</strong> ${config.generatedBy}
      </div>
      <div style="text-align: right;">
        <strong>Date Range:</strong> ${dateRangeText}<br>
        <strong>Generated:</strong> ${formatDateTime(config.generatedAt)}
      </div>
    </div>
  </div>
  
  ${sections.map(section => renderSection(section)).join('\n')}
  
  <div class="footer">
    <p>This is an automated report generated by FreedomCamp Manager.</p>
    <p>For questions or concerns, please contact your system administrator.</p>
  </div>
</body>
</html>
  `

  return html
}

function renderSection(section: PDFSection): string {
  switch (section.type) {
    case 'table':
      return renderTableSection(section)
    case 'list':
      return renderListSection(section)
    default:
      return renderTextSection(section)
  }
}

function renderTextSection(section: PDFSection): string {
  const content = Array.isArray(section.content) 
    ? section.content.join('<br>') 
    : typeof section.content === 'string'
    ? section.content
    : JSON.stringify(section.content, null, 2)

  return `
    <div class="section">
      <h2>${section.heading}</h2>
      <p>${content}</p>
    </div>
  `
}

function renderListSection(section: PDFSection): string {
  const items = Array.isArray(section.content) ? section.content : [section.content]
  
  return `
    <div class="section">
      <h2>${section.heading}</h2>
      <ul>
        ${items.map(item => `<li>${item}</li>`).join('\n')}
      </ul>
    </div>
  `
}

function renderTableSection(section: PDFSection): string {
  if (!Array.isArray(section.content)) {
    return renderTextSection(section)
  }

  const rows = section.content as any[]
  if (rows.length === 0) {
    return `
      <div class="section">
        <h2>${section.heading}</h2>
        <p>No data available.</p>
      </div>
    `
  }

  const headers = Object.keys(rows[0])
  
  return `
    <div class="section">
      <h2>${section.heading}</h2>
      <table>
        <thead>
          <tr>
            ${headers.map(h => `<th>${formatHeaderName(h)}</th>`).join('')}
          </tr>
        </thead>
        <tbody>
          ${rows.map(row => `
            <tr>
              ${headers.map(h => `<td>${formatCellValue(row[h])}</td>`).join('')}
            </tr>
          `).join('')}
        </tbody>
      </table>
    </div>
  `
}

function formatHeaderName(name: string): string {
  return name
    .replace(/_/g, ' ')
    .replace(/\b\w/g, l => l.toUpperCase())
}

function formatCellValue(value: any): string {
  if (value === null || value === undefined) return '-'
  if (typeof value === 'boolean') return value ? 'Yes' : 'No'
  if (value instanceof Date) return formatDate(value)
  return String(value)
}

function formatDate(date: Date): string {
  return date.toLocaleDateString('en-NZ', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    timeZone: 'Pacific/Auckland'
  })
}

function formatDateTime(date: Date): string {
  return date.toLocaleString('en-NZ', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    timeZone: 'Pacific/Auckland'
  })
}

/**
 * Export report as PDF using browser print dialog
 */
export function exportReportPDF(
  config: PDFReportConfig,
  sections: PDFSection[]
): void {
  const html = generateReportHTML(config, sections)
  
  // Create new window
  const printWindow = window.open('', '_blank')
  if (!printWindow) {
    throw new Error('Failed to open print window. Please allow popups.')
  }

  // Write HTML
  printWindow.document.write(html)
  printWindow.document.close()

  // Wait for load, then print
  printWindow.onload = () => {
    printWindow.focus()
    printWindow.print()
  }
}

/**
 * Generate compliance summary report
 */
export async function exportComplianceReport(
  organizationName: string,
  generatedBy: string,
  dateRange: { from: Date; to: Date },
  data: {
    summary: Record<string, number>
    vehicles: any[]
    breaches: any[]
    zones: any[]
  }
): Promise<void> {
  const config: PDFReportConfig = {
    title: 'Compliance Summary Report',
    subtitle: 'Freedom Camping Compliance Analysis',
    organizationName,
    generatedBy,
    generatedAt: new Date(),
    dateRange,
  }

  const sections: PDFSection[] = [
    {
      heading: 'Executive Summary',
      content: [
        `Total Observations: ${data.summary.total_observations || 0}`,
        `Compliant: ${data.summary.compliant || 0} (${((data.summary.compliant / data.summary.total_observations) * 100).toFixed(1)}%)`,
        `Breaches: ${data.summary.breaches || 0}`,
        `Unique Vehicles: ${data.summary.unique_vehicles || 0}`,
        `Active Enforcement: ${data.summary.active_enforcement || 0}`,
      ],
      type: 'list'
    },
    {
      heading: 'Top Breach Vehicles',
      content: data.vehicles.slice(0, 10),
      type: 'table'
    },
    {
      heading: 'Zone Activity',
      content: data.zones,
      type: 'table'
    },
    {
      heading: 'Recent Breaches',
      content: data.breaches.slice(0, 20),
      type: 'table'
    },
  ]

  exportReportPDF(config, sections)
}
