import { serve } from 'https://deno.land/std@0.177.0/http/server.ts';
import { SMTPClient } from 'https://deno.land/x/denomailer@1.0.0/mod.ts';
import { corsHeaders } from '../_shared/cors.ts';

const safeErrorText = (value: unknown) => String(value ?? '').replace(/[\r\n]+/g, ' ').slice(0, 500);

const classifySmtpError = (error: unknown) => {
  const raw = safeErrorText((error as any)?.message || error);
  const lowered = raw.toLowerCase();

  if (/(authentication failed|invalid login|535|auth failed|bad credentials)/i.test(raw)) {
    return {
      code: 'SMTP_AUTH_FAILED',
      message: 'SMTP authentication failed. Verify SMTP_USERNAME and SMTP_PASSWORD (use a Zoho app password if 2FA is enabled).',
    };
  }

  if (/(relay|relaying disallowed|sender address rejected|mail from|not allowed to send)/i.test(raw)) {
    return {
      code: 'SMTP_RELAY_DENIED',
      message: 'SMTP relay denied. Ensure SMTP_FROM_EMAIL matches the authenticated SMTP account.',
    };
  }

  if (/(timed out|timeout|econnrefused|connection refused|network is unreachable|could not connect)/i.test(raw)) {
    return {
      code: 'SMTP_CONNECT_FAILED',
      message: 'Could not connect to SMTP server. Check SMTP_HOST, SMTP_PORT, firewall rules, and TLS/SSL settings.',
    };
  }

  return {
    code: 'SMTP_SEND_FAILED',
    message: 'Failed to send invite email due to an SMTP provider error.',
  };
};

/**
 * send-invite-email
 *
 * Sends a user invite email with a sign-up link generated by create-user.
 * This is a dedicated function so that SMTP TLS does not exhaust the CPU
 * budget that create-user already uses for auth user creation.
 *
 * Required Supabase secrets:
 *   SMTP_HOST, SMTP_PORT, SMTP_USERNAME, SMTP_PASSWORD, SMTP_FROM_EMAIL
 *
 * Request body:
 *   email       string   Recipient email address
 *   first_name  string   Recipient first name (used in greeting)
 *   invite_url  string   Supabase invite link from generateLink
 */

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    const smtpHost     = Deno.env.get('SMTP_HOST');
    const smtpPort     = parseInt(Deno.env.get('SMTP_PORT') ?? '587', 10);
    const smtpUser     = Deno.env.get('SMTP_USERNAME');
    const smtpPass     = Deno.env.get('SMTP_PASSWORD');
    const smtpFrom     = Deno.env.get('SMTP_FROM_EMAIL');
    const smtpFromName = Deno.env.get('SMTP_FROM_NAME') ?? 'FreedomCamp Manager';
    const siteUrl      = Deno.env.get('SITE_URL') ?? 'https://fcmanager.co.nz';

    if (!smtpHost || !smtpUser || !smtpPass || !smtpFrom) {
      return new Response(
        JSON.stringify({ error: 'SMTP not configured. Set SMTP_HOST, SMTP_USERNAME, SMTP_PASSWORD, SMTP_FROM_EMAIL secrets.' }),
        { status: 503, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    if (smtpFrom.toLowerCase() !== smtpUser.toLowerCase()) {
      return new Response(
        JSON.stringify({
          error: 'SMTP_FROM_EMAIL must match SMTP_USERNAME for reliable delivery (prevents relay rejection).',
          code: 'SMTP_FROM_MISMATCH',
        }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const { email, first_name, invite_url } = await req.json();

    if (!email || !invite_url) {
      return new Response(
        JSON.stringify({ error: 'email and invite_url are required' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const greeting = first_name ? `Hi ${first_name},` : 'Hi,';

    const html = `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f4f4f5;font-family:Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f4f5;padding:40px 0;">
    <tr><td align="center">
      <table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08);">
        <tr>
          <td style="background:#1e3a5f;padding:32px 40px;">
            <h1 style="color:#ffffff;margin:0;font-size:22px;font-weight:700;">FreedomCamp Manager</h1>
            <p style="color:#93c5fd;margin:4px 0 0;font-size:13px;">Iron Eagle Security / OnSpace AI</p>
          </td>
        </tr>
        <tr>
          <td style="padding:40px;">
            <p style="font-size:16px;color:#374151;margin:0 0 16px;">${greeting}</p>
            <p style="font-size:15px;color:#374151;margin:0 0 16px;">
              You've been invited to join <strong>FreedomCamp Manager</strong>. Click the button below to set your password and access the platform.
            </p>
            <p style="text-align:center;margin:32px 0;">
              <a href="${invite_url}"
                 style="background:#1e3a5f;color:#ffffff;text-decoration:none;padding:14px 32px;border-radius:6px;font-size:15px;font-weight:600;display:inline-block;">
                Accept Invitation &amp; Set Password
              </a>
            </p>
            <p style="font-size:13px;color:#6b7280;margin:0 0 8px;">
              If the button above doesn't work, copy and paste this link into your browser:
            </p>
            <p style="font-size:12px;color:#374151;word-break:break-all;background:#f9fafb;padding:12px;border-radius:4px;margin:0 0 24px;">${invite_url}</p>
            <p style="font-size:13px;color:#ef4444;margin:0 0 24px;">
              ⚠ This link expires in <strong>24 hours</strong>.
            </p>
            <hr style="border:none;border-top:1px solid #e5e7eb;margin:24px 0;">
            <p style="font-size:12px;color:#9ca3af;margin:0;">
              If you weren't expecting this invitation, you can safely ignore this email.<br>
              Need help? Visit <a href="${siteUrl}" style="color:#1e3a5f;">${siteUrl}</a>
            </p>
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`;

    const client = new SMTPClient({
      connection: {
        hostname: smtpHost,
        port: smtpPort,
        tls: smtpPort === 465,
        auth: { username: smtpUser, password: smtpPass },
      },
    });

    await client.send({
      from: `${smtpFromName} <${smtpFrom}>`,
      to: email,
      subject: "You've been invited to FreedomCamp Manager",
      html,
      content: `${greeting}\n\nYou've been invited to join FreedomCamp Manager.\n\nAccept your invitation and set your password here:\n${invite_url}\n\nThis link expires in 24 hours.\n\nIf you weren't expecting this invitation please ignore this email.`,
    });

    await client.close();

    console.log(`Invite email sent to ${email}`);
    return new Response(
      JSON.stringify({ message: 'Invite email sent' }),
      { status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error: any) {
    const classified = classifySmtpError(error);
    console.error('send-invite-email error:', {
      code: classified.code,
      message: classified.message,
      raw: safeErrorText(error?.message || error),
      stack: safeErrorText(error?.stack),
    });
    return new Response(
      JSON.stringify({ error: classified.message, code: classified.code }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
