export type Database = {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string;
          name: string;
          contact_email: string | null;
          contact_phone: string | null;
          enforcement_workflow: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          contact_email?: string | null;
          contact_phone?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          contact_email?: string | null;
          contact_phone?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      zones: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          description: string | null;
          self_contained_required: boolean;
          nights_per_month: number;
          max_consecutive_nights: number;
          geometry: any;
          location_lat: number | null;
          location_lng: number | null;
          is_active: boolean;
          day_visit_only: boolean;
          merged_into_zone_id: string | null;
          merged_at: string | null;
          allowed_days: string[] | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          name: string;
          description?: string | null;
          self_contained_required?: boolean;
          nights_per_month?: number;
          max_consecutive_nights?: number;
          geometry?: any;
          location_lat?: number | null;
          location_lng?: number | null;
          is_active?: boolean;
          day_visit_only?: boolean;
          merged_into_zone_id?: string | null;
          merged_at?: string | null;
          allowed_days?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          name?: string;
          description?: string | null;
          self_contained_required?: boolean;
          nights_per_month?: number;
          max_consecutive_nights?: number;
          geometry?: any;
          location_lat?: number | null;
          location_lng?: number | null;
          is_active?: boolean;
          day_visit_only?: boolean;
          merged_into_zone_id?: string | null;
          merged_at?: string | null;
          allowed_days?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      patrols: {
        Row: {
          id: string;
          organization_id: string;
          zone_id: string;
          patrol_date: string;
          shift: 'day' | 'night' | 'morning' | 'afternoon';
          assigned_to: string | null;
          checked_in_at: string | null;
          check_in_location_lat: number | null;
          check_in_location_lng: number | null;
          completed_at: string | null;
          status: 'scheduled' | 'in_progress' | 'completed' | 'cancelled';
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          zone_id: string;
          patrol_date: string;
          shift: 'day' | 'night' | 'morning' | 'afternoon';
          assigned_to?: string | null;
          checked_in_at?: string | null;
          check_in_location_lat?: number | null;
          check_in_location_lng?: number | null;
          completed_at?: string | null;
          status?: 'scheduled' | 'in_progress' | 'completed' | 'cancelled';
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<{
          id: string;
          organization_id: string;
          zone_id: string;
          patrol_date: string;
          shift: 'day' | 'night' | 'morning' | 'afternoon';
          assigned_to: string | null;
          checked_in_at: string | null;
          check_in_location_lat: number | null;
          check_in_location_lng: number | null;
          completed_at: string | null;
          status: 'scheduled' | 'in_progress' | 'completed' | 'cancelled';
          notes: string | null;
          created_at: string;
          updated_at: string;
        }>;
        Relationships: [];
      };
      breach_alerts: {
        Row: {
          id: string;
          organization_id: string;
          patrol_id: string | null;
          vehicle_record_id: string | null; // Deprecated - use observation_id
          observation_id: string | null; // New - links to vehicle_observations
          compliance_result_id: string | null;
          zone_id: string;
          breach_type: 'overstay' | 'no_self_contained' | 'no_wof' | 'consecutive_days' | 'unauthorized_zone' | 'nights_exceeded';
          breach_details: any;
          due_date: string | null;
          notification_sent: boolean;
          notification_method: string | null;
          notified_at: string | null;
          notified_by: string | null;
          status: 'pending' | 'notified' | 'resolved' | 'escalated' | 'acknowledged' | 'enforcement_started' | 'dismissed';
          plate_number: string | null;
          assigned_to: string | null;
          assigned_at: string | null;
          admin_reviewed_by: string | null;
          admin_reviewed_at: string | null;
          resolution_notes: string | null;
          resolved_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          patrol_id?: string | null;
          vehicle_record_id?: string | null;
          observation_id?: string | null;
          zone_id: string;
          breach_type: 'overstay' | 'no_self_contained' | 'no_wof' | 'consecutive_days' | 'unauthorized_zone' | 'nights_exceeded';
          breach_details: any;
          due_date?: string | null;
          notification_sent?: boolean;
          notification_method?: string | null;
          notified_at?: string | null;
          notified_by?: string | null;
          status?: 'pending' | 'notified' | 'resolved' | 'escalated';
          resolution_notes?: string | null;
          resolved_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<{
          id: string;
          organization_id: string;
          patrol_id: string | null;
          vehicle_record_id: string | null;
          observation_id: string | null;
          zone_id: string;
          breach_type: 'overstay' | 'no_self_contained' | 'no_wof' | 'consecutive_days' | 'unauthorized_zone' | 'nights_exceeded';
          breach_details: any;
          due_date: string | null;
          notification_sent: boolean;
          notification_method: string | null;
          notified_at: string | null;
          notified_by: string | null;
          status: 'pending' | 'notified' | 'resolved' | 'escalated';
          resolution_notes: string | null;
          resolved_at: string | null;
          created_at: string;
          updated_at: string;
        }>;
        Relationships: [];
      };
      // ⚠️ vehicle_records DEPRECATED - Use vehicle_observations instead
      // This type is kept for backward compatibility only
      // All new code should use vehicle_observations
      health_safety_reports: {
        Row: {
          id: string;
          organization_id: string;
          zone_id: string;
          reported_by: string;
          patrol_id: string | null;
          details: string;
          severity: 'low' | 'medium' | 'high' | 'critical';
          status: 'pending' | 'under_review' | 'resolved';
          location_lat: number | null;
          location_lng: number | null;
          attachments: any;
          resolution_notes: string | null;
          resolved_by: string | null;
          resolved_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          zone_id: string;
          reported_by: string;
          patrol_id?: string | null;
          details: string;
          severity: 'low' | 'medium' | 'high' | 'critical';
          status?: 'pending' | 'under_review' | 'resolved';
          location_lat?: number | null;
          location_lng?: number | null;
          attachments?: any;
          resolution_notes?: string | null;
          resolved_by?: string | null;
          resolved_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<{
          id: string;
          organization_id: string;
          zone_id: string;
          reported_by: string;
          patrol_id: string | null;
          details: string;
          severity: 'low' | 'medium' | 'high' | 'critical';
          status: 'pending' | 'under_review' | 'resolved';
          location_lat: number | null;
          location_lng: number | null;
          attachments: any;
          resolution_notes: string | null;
          resolved_by: string | null;
          resolved_at: string | null;
          created_at: string;
          updated_at: string;
        }>;
        Relationships: [];
      };
      incidents: {
        Row: {
          id: string;
          organization_id: string;
          user_id: string;
          zone_id: string;
          vehicle_id: string | null;
          enforcement_action_id: string | null;
          incident_type: string;
          description: string;
          status: 'pending' | 'investigating' | 'resolved' | 'closed' | 'open' | 'under_review';
          severity: 'low' | 'medium' | 'high' | 'critical';
          resolution_notes: string | null;
          resolved_by: string | null;
          location_lat: number | null;
          location_lng: number | null;
          attachments: string[];
          recorded_at: string;
          resolved_at: string | null;
          created_at: string;
          updated_at: string;
          photos: string[] | null;
          photo_hashes: string[] | null;
          photo_metadata_ids: string[] | null;
          gps_latitude: number | null;
          gps_longitude: number | null;
          gps_accuracy: number | null;
          happened_at: string | null;
          court_ready: boolean;
          approved_by: string | null;
          approved_at: string | null;
          evidence_notes: string | null;
          homeless_status: 'claimed' | 'confirmed' | 'none' | null;
          hs_issues: boolean;
          issue_detected: boolean;
          enforcement_required: boolean;
        };
        Insert: {
          id?: string;
          organization_id: string;
          user_id: string;
          zone_id: string;
          vehicle_id?: string | null;
          enforcement_action_id?: string | null;
          incident_type: string;
          description: string;
          status?: 'pending' | 'investigating' | 'resolved' | 'closed' | 'open' | 'under_review';
          severity?: 'low' | 'medium' | 'high' | 'critical';
          resolution_notes?: string | null;
          resolved_by?: string | null;
          location_lat?: number | null;
          location_lng?: number | null;
          attachments?: string[];
          recorded_at?: string;
          resolved_at?: string | null;
          created_at?: string;
          updated_at?: string;
          photos?: string[] | null;
          photo_hashes?: string[] | null;
          photo_metadata_ids?: string[] | null;
          gps_latitude?: number | null;
          gps_longitude?: number | null;
          gps_accuracy?: number | null;
          happened_at?: string | null;
          court_ready?: boolean;
          approved_by?: string | null;
          approved_at?: string | null;
          evidence_notes?: string | null;
          homeless_status?: 'claimed' | 'confirmed' | 'none' | null;
          hs_issues?: boolean;
          issue_detected?: boolean;
          enforcement_required?: boolean;
        };
        Update: Partial<{
          id: string;
          organization_id: string;
          user_id: string;
          zone_id: string;
          vehicle_id: string | null;
          enforcement_action_id: string | null;
          incident_type: string;
          description: string;
          status: 'pending' | 'investigating' | 'resolved' | 'closed' | 'open' | 'under_review';
          severity: 'low' | 'medium' | 'high' | 'critical';
          resolution_notes: string | null;
          resolved_by: string | null;
          location_lat: number | null;
          location_lng: number | null;
          attachments: string[];
          recorded_at: string;
          resolved_at: string | null;
          created_at: string;
          updated_at: string;
          photos: string[] | null;
          photo_hashes: string[] | null;
          photo_metadata_ids: string[] | null;
          gps_latitude: number | null;
          gps_longitude: number | null;
          gps_accuracy: number | null;
          happened_at: string | null;
          court_ready: boolean;
          approved_by: string | null;
          approved_at: string | null;
          evidence_notes: string | null;
          homeless_status: 'claimed' | 'confirmed' | 'none' | null;
          hs_issues: boolean;
          issue_detected: boolean;
          enforcement_required: boolean;
        }>;
        Relationships: [];
      };
      user_profiles: {
        Row: {
          id: string;
          organization_id: string | null;
          first_name: string;
          last_name: string;
          email: string;
          role: string;
          phone: string | null;
          is_active: boolean;
          employer_organization_id: string | null;
          authorized_work_locations: string[] | null;
          permissions: ('super_delete' | 'admin' | 'master' | 'officer')[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          organization_id?: string | null;
          first_name: string;
          last_name: string;
          email: string;
          role: string;
          phone?: string | null;
          is_active?: boolean;
          permissions?: ('super_delete' | 'admin' | 'master' | 'officer')[];
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<{
          id: string;
          organization_id: string | null;
          first_name: string;
          last_name: string;
          email: string;
          role: string;
          phone: string | null;
          is_active: boolean;
          permissions: ('super_delete' | 'admin' | 'master' | 'officer')[];
          created_at: string;
          updated_at: string;
        }>;
        Relationships: [];
      };
      verification_results: {
        Row: {
          id: string;
          organization_id: string;
          vehicle_record_id: string;
          zone_id: string;
          patrol_id: string | null;
          verified_by: string;
          stayed_overnight: boolean;
          meets_requirements: boolean;
          days_stayed: number | null;
          consecutive_days: number | null;
          breach_detected: boolean;
          breach_type: string | null;
          verification_details: any;
          location_lat: number | null;
          location_lng: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          vehicle_record_id: string;
          zone_id: string;
          patrol_id?: string | null;
          verified_by: string;
          stayed_overnight: boolean;
          meets_requirements: boolean;
          days_stayed?: number | null;
          consecutive_days?: number | null;
          breach_detected?: boolean;
          breach_type?: string | null;
          verification_details?: any;
          location_lat?: number | null;
          location_lng?: number | null;
          created_at?: string;
        };
        Update: Partial<{
          id: string;
          organization_id: string;
          vehicle_record_id: string;
          zone_id: string;
          patrol_id: string | null;
          verified_by: string;
          stayed_overnight: boolean;
          meets_requirements: boolean;
          days_stayed: number | null;
          consecutive_days: number | null;
          breach_detected: boolean;
          breach_type: string | null;
          verification_details: any;
          location_lat: number | null;
          location_lng: number | null;
          created_at: string;
        }>;
        Relationships: [];
      };
      audit_log: {
        Row: {
          id: string;
          organization_id: string | null;
          user_id: string | null;
          action: string;
          entity_type: string;
          entity_id: string | null;
          old_values: any;
          new_values: any;
          ip_address: string | null;
          user_agent: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id?: string | null;
          user_id?: string | null;
          action: string;
          entity_type: string;
          entity_id?: string | null;
          old_values?: any;
          new_values?: any;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Update: Partial<{
          id: string;
          organization_id: string | null;
          user_id: string | null;
          action: string;
          entity_type: string;
          entity_id: string | null;
          old_values: any;
          new_values: any;
          ip_address: string | null;
          user_agent: string | null;
          created_at: string;
        }>;
        Relationships: [];
      };
      plate_history: {
        Row: {
          id: string;
          plate_number: string;
          zone_id: string;
          seen_at: string;
          location_lat: number | null;
          location_lng: number | null;
          recorded_by: string | null;
          patrol_id: string | null;
          stayed_overnight: boolean | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          plate_number: string;
          zone_id: string;
          seen_at: string;
          location_lat?: number | null;
          location_lng?: number | null;
          recorded_by?: string | null;
          patrol_id?: string | null;
          stayed_overnight?: boolean | null;
          created_at?: string;
        };
        Update: Partial<{
          id: string;
          plate_number: string;
          zone_id: string;
          seen_at: string;
          location_lat: number | null;
          location_lng: number | null;
          recorded_by: string | null;
          patrol_id: string | null;
          stayed_overnight: boolean | null;
          created_at: string;
        }>;
        Relationships: [];
      };
      canonical_vehicles: {
        Row: {
          vehicle_id: string;
          plate_number: string;
          vehicle_make: string | null;
          vehicle_model: string | null;
          vehicle_color: string | null;
          vehicle_year: number | null;
          make: string | null;
          model: string | null;
          colour: string | null;
          self_contained: boolean | null;
          self_contained_expiry: string | null;
          homeless_status: string | null;
          profile_photo_url: string | null;
          profile_photo: string | null;
          profile_photo_score: number | null;
          profile_photo_updated_at: string | null;
          total_breaches: number | null;
          first_seen_at: string;
          last_seen_at: string;
          total_observations: number;
          is_homeless: boolean;
          homeless_confirmed: boolean;
          homeless_confirmed_by: string | null;
          homeless_confirmed_at: string | null;
          homeless_notes: string | null;
          is_flagged: boolean;
          flagged_priority: string | null;
          flagged_reason: string | null;
          flagged_notes: string | null;
          flagged_at: string | null;
          flagged_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          vehicle_id?: string;
          plate_number: string;
          vehicle_make?: string | null;
          vehicle_model?: string | null;
          vehicle_color?: string | null;
          first_seen_at?: string;
          last_seen_at?: string;
          total_observations?: number;
          is_homeless?: boolean;
          homeless_confirmed?: boolean;
          homeless_confirmed_by?: string | null;
          homeless_confirmed_at?: string | null;
          homeless_notes?: string | null;
          is_flagged?: boolean;
          flagged_priority?: string | null;
          flagged_reason?: string | null;
          flagged_notes?: string | null;
          flagged_at?: string | null;
          flagged_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<{
          vehicle_id: string;
          plate_number: string;
          vehicle_make: string | null;
          vehicle_model: string | null;
          vehicle_color: string | null;
          first_seen_at: string;
          last_seen_at: string;
          total_observations: number;
          is_homeless: boolean;
          homeless_confirmed: boolean;
          homeless_confirmed_by: string | null;
          homeless_confirmed_at: string | null;
          homeless_notes: string | null;
          is_flagged: boolean;
          flagged_priority: string | null;
          flagged_reason: string | null;
          flagged_notes: string | null;
          flagged_at: string | null;
          flagged_by: string | null;
          created_at: string;
          updated_at: string;
        }>;
        Relationships: [];
      };
      vehicle_observations: {
        Row: {
          id: string;
          observation_id: string;
          vehicle_id: string;
          plate_number: string | null;
          organization_id: string | null;
          zone_id: string;
          recorded_by: string | null;
          recorded_at: string;
          source_type: 'patrol' | 'scan' | 'import' | 'migration' | null;
          is_self_contained: boolean;
          is_compliant: boolean;
          gps_latitude: number | null;
          gps_longitude: number | null;
          gps_accuracy: number | null;
          evidence_photos: any;
          notes: string | null;
          original_record_id: string | null;
          created_at: string;
          // Enhanced fields from vehicle_records consolidation
          vehicle_make: string | null;
          vehicle_model: string | null;
          vehicle_color: string | null;
          vehicle_year: string | null;
          plate_input_method: string | null;
          homeless_claimed: boolean;
          homeless_confirmed: boolean;
          homeless_confirmed_by: string | null;
          homeless_confirmed_at: string | null;
          behavioral_flags: any;
          requires_followup: boolean;
          followup_reason: string | null;
          followup_priority: 'low' | 'medium' | 'high' | 'urgent' | null;
          followup_resolved: boolean;
          followup_resolved_by: string | null;
          followup_resolved_at: string | null;
          followup_resolution_notes: string | null;
          incident_id: string | null;
          investigation_job_id: string | null;
          health_safety_report_id: string | null;
          weather_conditions: string | null;
          photo_hashes: string[] | null;
          photo_metadata_ids: string[] | null;
          compliance_checked_at: string | null;
          compliance_matrix_version: number | null;
          evidence_timestamp: string;
        };
        Insert: {
          observation_id?: string;
          vehicle_id: string;
          organization_id?: string | null;
          zone_id: string;
          recorded_by?: string | null;
          recorded_at?: string;
          source_type?: 'patrol' | 'scan' | 'import' | 'migration' | null;
          is_self_contained?: boolean;
          is_compliant?: boolean;
          gps_latitude?: number | null;
          gps_longitude?: number | null;
          gps_accuracy?: number | null;
          evidence_photos?: any;
          notes?: string | null;
          original_record_id?: string | null;
          created_at?: string;
          vehicle_make?: string | null;
          vehicle_model?: string | null;
          vehicle_color?: string | null;
          vehicle_year?: string | null;
          plate_input_method?: string | null;
          homeless_claimed?: boolean;
          homeless_confirmed?: boolean;
          homeless_confirmed_by?: string | null;
          homeless_confirmed_at?: string | null;
          behavioral_flags?: any;
          requires_followup?: boolean;
          followup_reason?: string | null;
          followup_priority?: 'low' | 'medium' | 'high' | 'urgent' | null;
          followup_resolved?: boolean;
          followup_resolved_by?: string | null;
          followup_resolved_at?: string | null;
          followup_resolution_notes?: string | null;
          incident_id?: string | null;
          investigation_job_id?: string | null;
          health_safety_report_id?: string | null;
          weather_conditions?: string | null;
          photo_hashes?: string[] | null;
          photo_metadata_ids?: string[] | null;
          compliance_checked_at?: string | null;
          compliance_matrix_version?: number | null;
          evidence_timestamp?: string;
        };
        Update: Partial<{
          observation_id: string;
          vehicle_id: string;
          organization_id: string | null;
          zone_id: string;
          recorded_by: string | null;
          recorded_at: string;
          source_type: 'patrol' | 'scan' | 'import' | 'migration' | null;
          is_self_contained: boolean;
          is_compliant: boolean;
          gps_latitude: number | null;
          gps_longitude: number | null;
          gps_accuracy: number | null;
          evidence_photos: any;
          notes: string | null;
          original_record_id: string | null;
          created_at: string;
          vehicle_make: string | null;
          vehicle_model: string | null;
          vehicle_color: string | null;
          vehicle_year: string | null;
          plate_input_method: string | null;
          homeless_claimed: boolean;
          homeless_confirmed: boolean;
          homeless_confirmed_by: string | null;
          homeless_confirmed_at: string | null;
          behavioral_flags: any;
          requires_followup: boolean;
          followup_reason: string | null;
          followup_priority: 'low' | 'medium' | 'high' | 'urgent' | null;
          followup_resolved: boolean;
          followup_resolved_by: string | null;
          followup_resolved_at: string | null;
          followup_resolution_notes: string | null;
          incident_id: string | null;
          investigation_job_id: string | null;
          health_safety_report_id: string | null;
          weather_conditions: string | null;
          photo_hashes: string[] | null;
          photo_metadata_ids: string[] | null;
          compliance_checked_at: string | null;
          compliance_matrix_version: number | null;
          evidence_timestamp: string;
        }>;
        Relationships: [];
      };
      compliance_results: {
        Row: {
          id: string;
          observation_id: string | null;
          vehicle_id: string | null;
          zone_id: string;
          organization_id: string | null;
          matrix_id: string | null;
          matrix_version: number | null;
          is_compliant: boolean;
          violation_reasons: string[];
          metrics_json: any;
          matrix_snapshot: any;
          evaluated_at: string;
          created_at: string;
          // GPS-verified fields
          after_hours_violation: boolean | null;
          stay_confirmed_by_gps: boolean | null;
          gps_verified_consecutive_nights: number | null;
          gps_evidence_json: any;
        };
        Insert: {
          id?: string;
          observation_id?: string | null;
          vehicle_id?: string | null;
          zone_id: string;
          organization_id?: string | null;
          matrix_id?: string | null;
          matrix_version?: number | null;
          is_compliant: boolean;
          violation_reasons?: string[];
          metrics_json?: any;
          matrix_snapshot: any;
          evaluated_at?: string;
          created_at?: string;
          after_hours_violation?: boolean | null;
          stay_confirmed_by_gps?: boolean | null;
          gps_verified_consecutive_nights?: number | null;
          gps_evidence_json?: any;
        };
        Update: Partial<{
          id: string;
          observation_id: string | null;
          vehicle_id: string | null;
          zone_id: string;
          organization_id: string | null;
          matrix_id: string | null;
          matrix_version: number | null;
          is_compliant: boolean;
          violation_reasons: string[];
          metrics_json: any;
          matrix_snapshot: any;
          evaluated_at: string;
          created_at: string;
          after_hours_violation: boolean | null;
          stay_confirmed_by_gps: boolean | null;
          gps_verified_consecutive_nights: number | null;
          gps_evidence_json: any;
        }>;
        Relationships: [];
      };
      zone_compliance_matrix: {
        Row: {
          id: string;
          zone_id: string;
          organization_id: string;
          version: number;
          effective_from: string;
          effective_to: string | null;
          self_contained_required: boolean;
          nights_per_month: number;
          max_consecutive_nights: number;
          day_visit_only: boolean;
          allowed_days: any;
          homeless_exemption: boolean;
          created_by: string | null;
          change_reason: string | null;
          change_notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          zone_id: string;
          organization_id: string;
          version: number;
          effective_from?: string;
          effective_to?: string | null;
          self_contained_required?: boolean;
          nights_per_month?: number;
          max_consecutive_nights?: number;
          day_visit_only?: boolean;
          allowed_days?: any;
          homeless_exemption?: boolean;
          created_by?: string | null;
          change_reason?: string | null;
          change_notes?: string | null;
          created_at?: string;
        };
        Update: Partial<{
          id: string;
          zone_id: string;
          organization_id: string;
          version: number;
          effective_from: string;
          effective_to: string | null;
          self_contained_required: boolean;
          nights_per_month: number;
          max_consecutive_nights: number;
          day_visit_only: boolean;
          allowed_days: any;
          homeless_exemption: boolean;
          created_by: string | null;
          change_reason: string | null;
          change_notes: string | null;
          created_at: string;
        }>;
        Relationships: [];
      };
      drift_events: {
        Row: {
          id: string;
          zone_id: string;
          organization_id: string;
          matrix_version_from: number | null;
          matrix_version_to: number | null;
          matrix_id_from: string | null;
          matrix_id_to: string | null;
          observations_affected: number;
          compliance_changed: number;
          criteria_changed: any;
          detected_at: string;
          detected_by: string | null;
          status: 'pending' | 'reviewed' | 'resolved';
          remediation_notes: string | null;
          reviewed_at: string | null;
          reviewed_by: string | null;
        };
        Insert: {
          id?: string;
          zone_id: string;
          organization_id: string;
          matrix_version_from?: number | null;
          matrix_version_to?: number | null;
          matrix_id_from?: string | null;
          matrix_id_to?: string | null;
          observations_affected?: number;
          compliance_changed?: number;
          criteria_changed?: any;
          detected_at?: string;
          detected_by?: string | null;
          status?: 'pending' | 'reviewed' | 'resolved';
          remediation_notes?: string | null;
          reviewed_at?: string | null;
          reviewed_by?: string | null;
        };
        Update: Partial<{
          id: string;
          zone_id: string;
          organization_id: string;
          matrix_version_from: number | null;
          matrix_version_to: number | null;
          matrix_id_from: string | null;
          matrix_id_to: string | null;
          observations_affected: number;
          compliance_changed: number;
          criteria_changed: any;
          detected_at: string;
          detected_by: string | null;
          status: 'pending' | 'reviewed' | 'resolved';
          remediation_notes: string | null;
          reviewed_at: string | null;
          reviewed_by: string | null;
        }>;
        Relationships: [];
      };
      admin_recalculation_actions: {
        Row: {
          id: string;
          scope_type: 'ZONE' | 'ORG' | 'BUILD';
          target_zone_ids: string[] | null;
          target_org_ids: string[] | null;
          date_range_start: string | null;
          date_range_end: string | null;
          observations_processed: number;
          compliance_changed: number;
          drift_events_created: number;
          status: 'running' | 'completed' | 'failed';
          error_message: string | null;
          performed_by: string | null;
          performed_at: string;
          completed_at: string | null;
          duration_seconds: number | null;
        };
        Insert: {
          id?: string;
          scope_type: 'ZONE' | 'ORG' | 'BUILD';
          target_zone_ids?: string[] | null;
          target_org_ids?: string[] | null;
          date_range_start?: string | null;
          date_range_end?: string | null;
          observations_processed?: number;
          compliance_changed?: number;
          drift_events_created?: number;
          status?: 'running' | 'completed' | 'failed';
          error_message?: string | null;
          performed_by?: string | null;
          performed_at?: string;
          completed_at?: string | null;
          duration_seconds?: number | null;
        };
        Update: Partial<{
          id: string;
          scope_type: 'ZONE' | 'ORG' | 'BUILD';
          target_zone_ids: string[] | null;
          target_org_ids: string[] | null;
          date_range_start: string | null;
          date_range_end: string | null;
          observations_processed: number;
          compliance_changed: number;
          drift_events_created: number;
          status: 'running' | 'completed' | 'failed';
          error_message: string | null;
          performed_by: string | null;
          performed_at: string;
          completed_at: string | null;
          duration_seconds: number | null;
        }>;
        Relationships: [];
      };
      photo_metadata: {
        Row: {
          id: string;
          photo_url: string;
          file_name: string;
          bucket_name: string;
          storage_path: string;
          photo_hash: string;
          photo_type: 'full' | 'cropped' | 'evidence';
          file_size_bytes: number | null;
          width: number | null;
          height: number | null;
          mime_type: string | null;
          organization_id: string | null;
          user_id: string | null;
          incident_id: string | null;
          vehicle_record_id: string | null;
          observation_id: string | null;
          retention_policy: string;
          court_ready: boolean;
          delete_after_days: number;
          scheduled_deletion_at: string | null;
          gps_latitude: number | null;
          gps_longitude: number | null;
          gps_accuracy: number | null;
          captured_at: string;
          uploaded_at: string;
          created_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          photo_url: string;
          file_name: string;
          bucket_name: string;
          storage_path: string;
          photo_hash: string;
          photo_type: 'full' | 'cropped' | 'evidence';
          file_size_bytes?: number | null;
          width?: number | null;
          height?: number | null;
          mime_type?: string | null;
          organization_id?: string | null;
          user_id?: string | null;
          incident_id?: string | null;
          vehicle_record_id?: string | null;
          observation_id?: string | null;
          retention_policy?: string;
          court_ready?: boolean;
          delete_after_days?: number;
          scheduled_deletion_at?: string | null;
          gps_latitude?: number | null;
          gps_longitude?: number | null;
          gps_accuracy?: number | null;
          captured_at?: string;
          uploaded_at?: string;
          created_at?: string;
          deleted_at?: string | null;
        };
        Update: Partial<{
          id: string;
          photo_url: string;
          file_name: string;
          bucket_name: string;
          storage_path: string;
          photo_hash: string;
          photo_type: 'full' | 'cropped' | 'evidence';
          file_size_bytes: number | null;
          width: number | null;
          height: number | null;
          mime_type: string | null;
          organization_id: string | null;
          user_id: string | null;
          incident_id: string | null;
          vehicle_record_id: string | null;
          observation_id: string | null;
          retention_policy: string;
          court_ready: boolean;
          delete_after_days: number;
          scheduled_deletion_at: string | null;
          gps_latitude: number | null;
          gps_longitude: number | null;
          gps_accuracy: number | null;
          captured_at: string;
          uploaded_at: string;
          created_at: string;
          deleted_at: string | null;
        }>;
        Relationships: [];
      };
      plate_scans: {
        Row: {
          id: string;
          organization_id: string;
          zone_id: string;
          scanned_by: string;
          plate_number: string;
          scan_mode: 'handheld' | 'driving';
          scanned_photo: string | null;
          confidence_score: number | null;
          gps_latitude: number | null;
          gps_longitude: number | null;
          gps_accuracy: number | null;
          ai_vehicle_make: string | null;
          ai_vehicle_model: string | null;
          ai_vehicle_color: string | null;
          ai_likely_self_contained: boolean;
          ai_detected_stickers: any;
          reviewed: boolean;
          reviewed_by: string | null;
          reviewed_at: string | null;
          review_notes: string | null;
          review_action: 'approved' | 'rejected' | 'needs_followup' | null;
          flagged_vehicle_detected: boolean;
          breach_detected: boolean;
          violation_summary: string | null;
          vehicle_record_id: string | null;
          converted_to_record: boolean;
          scanned_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          zone_id: string;
          scanned_by: string;
          plate_number: string;
          scan_mode: 'handheld' | 'driving';
          scanned_photo?: string | null;
          confidence_score?: number | null;
          gps_latitude?: number | null;
          gps_longitude?: number | null;
          gps_accuracy?: number | null;
          ai_vehicle_make?: string | null;
          ai_vehicle_model?: string | null;
          ai_vehicle_color?: string | null;
          ai_likely_self_contained?: boolean;
          ai_detected_stickers?: any;
          reviewed?: boolean;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          review_notes?: string | null;
          review_action?: 'approved' | 'rejected' | 'needs_followup' | null;
          flagged_vehicle_detected?: boolean;
          breach_detected?: boolean;
          violation_summary?: string | null;
          vehicle_record_id?: string | null;
          converted_to_record?: boolean;
          scanned_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<{
          id: string;
          organization_id: string;
          zone_id: string;
          scanned_by: string;
          plate_number: string;
          scan_mode: 'handheld' | 'driving';
          scanned_photo: string | null;
          confidence_score: number | null;
          gps_latitude: number | null;
          gps_longitude: number | null;
          gps_accuracy: number | null;
          ai_vehicle_make: string | null;
          ai_vehicle_model: string | null;
          ai_vehicle_color: string | null;
          ai_likely_self_contained: boolean;
          ai_detected_stickers: any;
          reviewed: boolean;
          reviewed_by: string | null;
          reviewed_at: string | null;
          review_notes: string | null;
          review_action: 'approved' | 'rejected' | 'needs_followup' | null;
          flagged_vehicle_detected: boolean;
          breach_detected: boolean;
          violation_summary: string | null;
          vehicle_record_id: string | null;
          converted_to_record: boolean;
          scanned_at: string;
          created_at: string;
          updated_at: string;
        }>;
        Relationships: [];
      };
      observations: {
        Row: {
          id: string;
          // observation_id is an alias for id used throughout the frontend
          observation_id: string;
          idempotency_key: string;
          plate_number: string;
          photo_url: string;
          photo_hash: string;
          recorded_at: string;
          zone_id: string;
          organization_id: string;
          gps_latitude: number;
          gps_longitude: number;
          gps_accuracy: number | null;
          recorded_by: string;
          officer_notes: string | null;
          notes: string | null;
          weather_conditions: string | null;
          vehicle_make: string | null;
          vehicle_model: string | null;
          vehicle_year: number | null;
          vehicle_color: string | null;
          self_contained: boolean;
          self_contained_expiry: string | null;
          is_compliant: boolean;
          is_self_contained: boolean | null;
          photo: string | null;
          breach_details: any | null;
          // is_breach is the inverse of is_compliant, kept for backwards compat
          is_breach: boolean | null;
          breach_type: string | null;
          evidence_photos: string[] | null;
          has_homeless_claim: boolean | null;
          breach_reason: string | null;
          nights_stayed_this_month: number;
          // nights_stayed is an alias for nights_stayed_this_month
          nights_stayed: number | null;
          consecutive_nights: number;
          // Optional fields used by compliance/homeless workflows
          is_flagged: boolean | null;
          flagged_reason: string | null;
          homeless_status: string | null;
          homeless_claimed: boolean | null;
          profile_photo: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          idempotency_key: string;
          plate_number: string;
          photo_url: string;
          photo_hash: string;
          recorded_at: string;
          zone_id: string;
          organization_id: string;
          gps_latitude: number;
          gps_longitude: number;
          gps_accuracy?: number | null;
          recorded_by: string;
          officer_notes?: string | null;
          weather_conditions?: string | null;
          vehicle_make?: string | null;
          vehicle_model?: string | null;
          vehicle_year?: number | null;
          vehicle_color?: string | null;
          self_contained?: boolean;
          self_contained_expiry?: string | null;
          is_compliant?: boolean;
          breach_type?: string | null;
          breach_reason?: string | null;
          nights_stayed_this_month?: number;
          consecutive_nights?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          idempotency_key?: string;
          plate_number?: string;
          photo_url?: string;
          photo_hash?: string;
          recorded_at?: string;
          zone_id?: string;
          organization_id?: string;
          gps_latitude?: number;
          gps_longitude?: number;
          gps_accuracy?: number | null;
          recorded_by?: string;
          officer_notes?: string | null;
          weather_conditions?: string | null;
          vehicle_make?: string | null;
          vehicle_model?: string | null;
          vehicle_year?: number | null;
          vehicle_color?: string | null;
          self_contained?: boolean;
          self_contained_expiry?: string | null;
          is_compliant?: boolean;
          breach_type?: string | null;
          breach_reason?: string | null;
          nights_stayed_this_month?: number;
          consecutive_nights?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      alert_queue: {
        Row: {
          id: string;
          organization_id: string;
          user_id: string;
          alert_type: string;
          priority: string;
          title: string;
          message: string;
          details: any | null;
          vehicle_id: string | null;
          zone_id: string | null;
          person_id: string | null;
          observation_id: string | null;
          status: string;
          read_at: string | null;
          expires_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          user_id: string;
          alert_type: string;
          priority: string;
          title: string;
          message: string;
          details?: any | null;
          vehicle_id?: string | null;
          zone_id?: string | null;
          person_id?: string | null;
          observation_id?: string | null;
          status?: string;
          read_at?: string | null;
          expires_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          user_id?: string;
          alert_type?: string;
          priority?: string;
          title?: string;
          message?: string;
          details?: any | null;
          vehicle_id?: string | null;
          zone_id?: string | null;
          person_id?: string | null;
          observation_id?: string | null;
          status?: string;
          read_at?: string | null;
          expires_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      alert_acknowledgements: {
        Row: {
          id: string;
          alert_id: string;
          user_id: string;
          acknowledged_at: string;
          acknowledgement_type: string;
          notes: string | null;
          action_taken: string | null;
          evidence_photos: string[] | null;
          report_created_id: string | null;
          follow_up_required: boolean;
          follow_up_date: string | null;
          gps_latitude: number | null;
          gps_longitude: number | null;
          device_info: any | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          alert_id: string;
          user_id: string;
          acknowledged_at?: string;
          acknowledgement_type: string;
          notes?: string | null;
          action_taken?: string | null;
          evidence_photos?: string[] | null;
          report_created_id?: string | null;
          follow_up_required?: boolean;
          follow_up_date?: string | null;
          gps_latitude?: number | null;
          gps_longitude?: number | null;
          device_info?: any | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          alert_id?: string;
          user_id?: string;
          acknowledged_at?: string;
          acknowledgement_type?: string;
          notes?: string | null;
          action_taken?: string | null;
          evidence_photos?: string[] | null;
          report_created_id?: string | null;
          follow_up_required?: boolean;
          follow_up_date?: string | null;
          gps_latitude?: number | null;
          gps_longitude?: number | null;
          device_info?: any | null;
          created_at?: string;
        };
        Relationships: [];
      };
      bug_reports: {
        Row: {
          id: string;
          organization_id: string | null;
          user_id: string;
          issue_type: string;
          severity: string;
          priority: string | null;
          title: string;
          description: string;
          steps_to_reproduce: string | null;
          expected_behavior: string | null;
          actual_behavior: string | null;
          app_version: string;
          user_role: string;
          current_page: string | null;
          browser_info: any;
          device_info: any;
          console_errors: any;
          network_status: string | null;
          screenshots: string[];
          screenshot_metadata: any;
          status: string;
          admin_notes: string | null;
          resolved_at: string | null;
          resolved_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id?: string | null;
          user_id: string;
          issue_type: string;
          severity?: string;
          priority?: string | null;
          title: string;
          description: string;
          steps_to_reproduce?: string | null;
          expected_behavior?: string | null;
          actual_behavior?: string | null;
          app_version: string;
          user_role: string;
          current_page?: string | null;
          browser_info?: any;
          device_info?: any;
          console_errors?: any;
          network_status?: string | null;
          screenshots?: string[];
          screenshot_metadata?: any;
          status?: string;
          admin_notes?: string | null;
          resolved_at?: string | null;
          resolved_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          status?: string;
          admin_notes?: string | null;
          resolved_at?: string | null;
          resolved_by?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      canonical_vehicle_sources: {
        Row: {
          id: string;
          plate_number: string;
          source_type: string;
          source_data: any | null;
          verified: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          plate_number: string;
          source_type: string;
          source_data?: any | null;
          verified?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          plate_number?: string;
          source_type?: string;
          source_data?: any | null;
          verified?: boolean;
          updated_at?: string;
        };
        Relationships: [];
      };
      "compliance-documents": {
        Row: {
          id: string;
          organization_id: string;
          user_id: string;
          document_type: string;
          document_url: string;
          document_number: string | null;
          expiry_date: string | null;
          verified: boolean;
          metadata: any | null;
          coa_number: string | null;
          coa_expiry_date: string | null;
          coa_document_url: string | null;
          has_warrant: boolean | null;
          warrant_number: string | null;
          warrant_expiry_date: string | null;
          warrant_document_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          user_id: string;
          document_type: string;
          document_url?: string;
          document_number?: string | null;
          expiry_date?: string | null;
          verified?: boolean;
          metadata?: any | null;
          coa_number?: string | null;
          coa_expiry_date?: string | null;
          coa_document_url?: string | null;
          has_warrant?: boolean | null;
          warrant_number?: string | null;
          warrant_expiry_date?: string | null;
          warrant_document_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          user_id?: string;
          document_type?: string;
          document_url?: string;
          document_number?: string | null;
          expiry_date?: string | null;
          verified?: boolean;
          metadata?: any | null;
          coa_number?: string | null;
          coa_expiry_date?: string | null;
          coa_document_url?: string | null;
          has_warrant?: boolean | null;
          warrant_number?: string | null;
          warrant_expiry_date?: string | null;
          warrant_document_url?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      dashboard_stats_live: {
        Row: {
          scans_today: number;
          active_breaches: number;
          unique_vehicles_24h: number;
          warnings_24h: number;
          active_officers: number;
          last_scan_time: string | null;
        };
        Insert: { scans_today?: number };
        Update: { scans_today?: number };
        Relationships: [];
      };
      dashboard_breaches: {
        Row: {
          alert_id: string;
          status: string;
          created_at: string;
          plate_number: string;
          make: string | null;
          model: string | null;
          breach_type: string | null;
          zone_name: string | null;
          organization_id: string | null;
        };
        Insert: { alert_id: string; status: string; created_at: string; plate_number: string };
        Update: { status?: string };
        Relationships: [];
      };
      enforcement_actions: {
        Row: {
          id: string;
          organization_id: string;
          action_type: string;
          plate_number: string | null;
          zone_id: string | null;
          assigned_to: string | null;
          assigned_at: string | null;
          status: string;
          breach_status: string | null;
          observation_id: string | null;
          compliance_result_id: string | null;
          breach_type: string | null;
          notes: string | null;
          location_lat: number | null;
          location_lng: number | null;
          recorded_at: string | null;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          action_type: string;
          plate_number?: string | null;
          zone_id?: string | null;
          assigned_to?: string | null;
          assigned_at?: string | null;
          status?: string;
          observation_id?: string | null;
          compliance_result_id?: string | null;
          breach_type?: string | null;
          notes?: string | null;
          recorded_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          action_type?: string;
          status?: string;
          assigned_to?: string | null;
          assigned_at?: string | null;
          notes?: string | null;
          completed_at?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      evidence: {
        Row: {
          id: string;
          organization_id: string;
          plate_number: string | null;
          observation_id: string | null;
          photo_url: string;
          photo_hash: string | null;
          caption: string | null;
          captured_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          plate_number?: string | null;
          observation_id?: string | null;
          photo_url: string;
          photo_hash?: string | null;
          caption?: string | null;
          captured_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          caption?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      flagged_vehicles: {
        Row: {
          id: string;
          plate_number: string;
          organization_id: string;
          reason: string | null;
          priority: string;
          flagged_by: string | null;
          status: string;
          notes: string | null;
          flagged_at: string | null;
          resolved_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          plate_number: string;
          organization_id: string;
          reason?: string | null;
          priority?: string;
          flagged_by?: string | null;
          status?: string;
          notes?: string | null;
          flagged_at?: string | null;
          resolved_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          reason?: string | null;
          priority?: string;
          status?: string;
          notes?: string | null;
          resolved_at?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      import_history: {
        Row: {
          id: string;
          organization_id: string;
          user_id: string;
          import_type: string;
          status: string;
          records_imported: number | null;
          records_failed: number | null;
          error_log: any | null;
          metadata: any | null;
          started_at: string;
          completed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          user_id: string;
          import_type: string;
          status?: string;
          records_imported?: number | null;
          records_failed?: number | null;
          error_log?: any | null;
          metadata?: any | null;
          started_at?: string;
          completed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          status?: string;
          records_imported?: number | null;
          records_failed?: number | null;
          error_log?: any | null;
          completed_at?: string | null;
        };
        Relationships: [];
      };
      "incident-evidence": {
        Row: {
          id: string;
          incident_id: string;
          organization_id: string;
          photo_url: string;
          photo_hash: string | null;
          caption: string | null;
          uploaded_by: string;
          uploaded_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          incident_id: string;
          organization_id: string;
          photo_url: string;
          photo_hash?: string | null;
          caption?: string | null;
          uploaded_by: string;
          uploaded_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          caption?: string | null;
        };
        Relationships: [];
      };
      investigation_findings: {
        Row: {
          id: string;
          job_id: string;
          organization_id: string;
          finding_type: string;
          description: string;
          evidence_urls: string[] | null;
          recorded_by: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          job_id: string;
          organization_id: string;
          finding_type: string;
          description: string;
          evidence_urls?: string[] | null;
          recorded_by: string;
          created_at?: string;
        };
        Update: {
          description?: string;
          evidence_urls?: string[] | null;
        };
        Relationships: [];
      };
      investigation_jobs: {
        Row: {
          id: string;
          organization_id: string;
          job_type: string;
          plate_number: string | null;
          zone_id: string | null;
          assigned_to: string | null;
          status: string;
          priority: string;
          notes: string | null;
          location_address: string | null;
          location_address: string | null;
          assigned_at: string | null;
          started_at: string | null;
          completed_at: string | null;
          breach_type: string | null;
          observation_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          job_type: string;
          plate_number?: string | null;
          zone_id?: string | null;
          assigned_to?: string | null;
          status?: string;
          priority?: string;
          notes?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          breach_type?: string | null;
          observation_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          status?: string;
          assigned_to?: string | null;
          notes?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      officer_activity_log: {
        Row: {
          id: string;
          user_id: string;
          organization_id: string;
          activity_type: string;
          gps_latitude: number | null;
          gps_longitude: number | null;
          gps_accuracy: number | null;
          metadata: any;
          recorded_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          organization_id: string;
          activity_type: string;
          gps_latitude?: number | null;
          gps_longitude?: number | null;
          gps_accuracy?: number | null;
          metadata?: any;
          recorded_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          activity_type?: string;
          metadata?: any;
        };
        Relationships: [];
      };
      officer_welfare_alerts: {
        Row: {
          id: string;
          officer_id: string;
          organization_id: string;
          alert_type: string;
          status: string;
          escalated_at: string | null;
          resolved_at: string | null;
          acknowledged_by: string | null;
          acknowledged_at: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          officer_id: string;
          organization_id: string;
          alert_type: string;
          status?: string;
          escalated_at?: string | null;
          resolved_at?: string | null;
          acknowledged_by?: string | null;
          acknowledged_at?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          status?: string;
          escalated_at?: string | null;
          resolved_at?: string | null;
          acknowledged_by?: string | null;
          acknowledged_at?: string | null;
          notes?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      officer_welfare_settings: {
        Row: {
          id: string;
          organization_id: string;
          user_id: string;
          auto_logoff_enabled: boolean;
          welfare_check_enabled: boolean;
          inactivity_warning_time: number;
          auto_logoff_time: number;
          gps_inactivity_threshold: number;
          admin_escalation_time: number;
          critical_escalation_time: number;
          investigation_exception_enabled: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          user_id: string;
          auto_logoff_enabled?: boolean;
          welfare_check_enabled?: boolean;
          inactivity_warning_time?: number;
          auto_logoff_time?: number;
          gps_inactivity_threshold?: number;
          admin_escalation_time?: number;
          critical_escalation_time?: number;
          investigation_exception_enabled?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          auto_logoff_enabled?: boolean;
          welfare_check_enabled?: boolean;
          inactivity_warning_time?: number;
          auto_logoff_time?: number;
          gps_inactivity_threshold?: number;
          admin_escalation_time?: number;
          critical_escalation_time?: number;
          investigation_exception_enabled?: boolean;
          updated_at?: string;
        };
        Relationships: [];
      };
      person_interactions: {
        Row: {
          id: string;
          person_id: string | null;
          user_id: string;
          organization_id: string;
          interaction_type: string;
          interaction_notes: string | null;
          zone_id: string | null;
          plate_number: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          person_id?: string | null;
          user_id: string;
          organization_id: string;
          interaction_type: string;
          interaction_notes?: string | null;
          zone_id?: string | null;
          plate_number?: string | null;
          created_at?: string;
        };
        Update: {
          interaction_notes?: string | null;
        };
        Relationships: [];
      };
      person_records: {
        Row: {
          id: string;
          organization_id: string;
          full_name: string | null;
          zone_id: string | null;
          tent_location_description: string | null;
          homeless_claimed: boolean;
          risk_level: string | null;
          notes: string | null;
          photo_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          full_name?: string | null;
          zone_id?: string | null;
          tent_location_description?: string | null;
          homeless_claimed?: boolean;
          risk_level?: string | null;
          notes?: string | null;
          photo_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string | null;
          zone_id?: string | null;
          tent_location_description?: string | null;
          homeless_claimed?: boolean;
          risk_level?: string | null;
          notes?: string | null;
          photo_url?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      user_sessions: {
        Row: {
          id: string;
          user_id: string;
          organization_id: string | null;
          device_info: any | null;
          login_at: string;
          last_activity_at: string | null;
          logout_at: string | null;
          ip_address: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          organization_id?: string | null;
          device_info?: any | null;
          login_at?: string;
          last_activity_at?: string | null;
          logout_at?: string | null;
          ip_address?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          last_activity_at?: string | null;
          logout_at?: string | null;
        };
        Relationships: [];
      };
      vehicle_monthly_stays: {
        Row: {
          id: string;
          plate_number: string;
          organization_id: string;
          zone_id: string;
          calendar_month: string;
          nights_stayed: number;
          consecutive_nights: number;
          last_observation_date: string | null;
          observation_ids: string[] | null;
          reset_at: string | null;
          last_reset_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          plate_number: string;
          organization_id: string;
          zone_id: string;
          calendar_month: string;
          nights_stayed?: number;
          consecutive_nights?: number;
          last_observation_date?: string | null;
          observation_ids?: string[] | null;
          reset_at?: string | null;
          last_reset_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          nights_stayed?: number;
          consecutive_nights?: number;
          last_observation_date?: string | null;
          observation_ids?: string[] | null;
          reset_at?: string | null;
          last_reset_at?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      vehicle_records: {
        Row: {
          id: string;
          plate_number: string;
          vehicle_make: string | null;
          vehicle_model: string | null;
          vehicle_year: number | null;
          vehicle_color: string | null;
          organization_id: string;
          zone_id: string | null;
          evidence_photos: string[] | null;
          recorded_at: string | null;
          notes: string | null;
          is_self_contained: boolean | null;
          self_contained_expiry: string | null;
          officer_id: string | null;
          gps_latitude: number | null;
          gps_longitude: number | null;
          homeless_claimed: boolean | null;
          homeless_confirmed: boolean | null;
          behavioral_flags: any | null;
          is_compliant: boolean | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          plate_number: string;
          vehicle_make?: string | null;
          vehicle_model?: string | null;
          vehicle_year?: number | null;
          vehicle_color?: string | null;
          organization_id: string;
          zone_id?: string | null;
          evidence_photos?: string[] | null;
          recorded_at?: string | null;
          notes?: string | null;
          is_self_contained?: boolean | null;
          self_contained_expiry?: string | null;
          officer_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          vehicle_make?: string | null;
          vehicle_model?: string | null;
          vehicle_year?: number | null;
          vehicle_color?: string | null;
          zone_id?: string | null;
          evidence_photos?: string[] | null;
          notes?: string | null;
          is_self_contained?: boolean | null;
          self_contained_expiry?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      zone_legal_config: {
        Row: {
          id: string;
          zone_id: string;
          organization_id: string;
          org_office_name: string;
          org_building: string | null;
          org_street_address: string;
          org_po_box: string | null;
          org_city: string;
          org_postcode: string;
          org_country: string;
          org_phone: string | null;
          org_fax: string | null;
          org_email: string | null;
          org_website: string | null;
          legal_description: string;
          land_act: string;
          land_owner: string;
          managing_authority: string | null;
          max_stay_nights: number;
          max_consecutive_nights: number;
          self_contained_required: boolean;
          breach_template: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          zone_id: string;
          organization_id: string;
          org_office_name: string;
          org_building?: string | null;
          org_street_address: string;
          org_po_box?: string | null;
          org_city: string;
          org_postcode: string;
          org_country?: string;
          org_phone?: string | null;
          org_fax?: string | null;
          org_email?: string | null;
          org_website?: string | null;
          legal_description: string;
          land_act: string;
          land_owner: string;
          managing_authority?: string | null;
          max_stay_nights?: number;
          max_consecutive_nights?: number;
          self_contained_required?: boolean;
          breach_template: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          org_office_name?: string;
          org_building?: string | null;
          org_street_address?: string;
          org_city?: string;
          org_postcode?: string;
          legal_description?: string;
          land_act?: string;
          land_owner?: string;
          managing_authority?: string | null;
          max_stay_nights?: number;
          max_consecutive_nights?: number;
          self_contained_required?: boolean;
          breach_template?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
  };
};
