export type Database = {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string;
          name: string;
          contact_email: string | null;
          contact_phone: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          contact_email?: string | null;
          contact_phone?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          contact_email?: string | null;
          contact_phone?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      zones: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          description: string | null;
          self_contained_required: boolean;
          nights_per_month: number;
          max_consecutive_nights: number;
          geometry: any;
          location_lat: number | null;
          location_lng: number | null;
          is_active: boolean;
          day_visit_only: boolean;
          merged_into_zone_id: string | null;
          merged_at: string | null;
          allowed_days: string[] | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          name: string;
          description?: string | null;
          self_contained_required?: boolean;
          nights_per_month?: number;
          max_consecutive_nights?: number;
          geometry?: any;
          location_lat?: number | null;
          location_lng?: number | null;
          is_active?: boolean;
          day_visit_only?: boolean;
          merged_into_zone_id?: string | null;
          merged_at?: string | null;
          allowed_days?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          name?: string;
          description?: string | null;
          self_contained_required?: boolean;
          nights_per_month?: number;
          max_consecutive_nights?: number;
          geometry?: any;
          location_lat?: number | null;
          location_lng?: number | null;
          is_active?: boolean;
          day_visit_only?: boolean;
          merged_into_zone_id?: string | null;
          merged_at?: string | null;
          allowed_days?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      patrols: {
        Row: {
          id: string;
          organization_id: string;
          zone_id: string;
          patrol_date: string;
          shift: 'day' | 'night' | 'morning' | 'afternoon';
          assigned_to: string | null;
          checked_in_at: string | null;
          check_in_location_lat: number | null;
          check_in_location_lng: number | null;
          completed_at: string | null;
          status: 'scheduled' | 'in_progress' | 'completed' | 'cancelled';
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          zone_id: string;
          patrol_date: string;
          shift: 'day' | 'night' | 'morning' | 'afternoon';
          assigned_to?: string | null;
          checked_in_at?: string | null;
          check_in_location_lat?: number | null;
          check_in_location_lng?: number | null;
          completed_at?: string | null;
          status?: 'scheduled' | 'in_progress' | 'completed' | 'cancelled';
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<{
          id: string;
          organization_id: string;
          zone_id: string;
          patrol_date: string;
          shift: 'day' | 'night' | 'morning' | 'afternoon';
          assigned_to: string | null;
          checked_in_at: string | null;
          check_in_location_lat: number | null;
          check_in_location_lng: number | null;
          completed_at: string | null;
          status: 'scheduled' | 'in_progress' | 'completed' | 'cancelled';
          notes: string | null;
          created_at: string;
          updated_at: string;
        }>;
      };
      breach_alerts: {
        Row: {
          id: string;
          organization_id: string;
          patrol_id: string | null;
          vehicle_record_id: string | null; // Deprecated - use observation_id
          observation_id: string | null; // New - links to vehicle_observations
          zone_id: string;
          breach_type: 'overstay' | 'no_self_contained' | 'no_wof' | 'consecutive_days' | 'unauthorized_zone' | 'nights_exceeded';
          breach_details: any;
          due_date: string | null;
          notification_sent: boolean;
          notification_method: string | null;
          notified_at: string | null;
          notified_by: string | null;
          status: 'pending' | 'notified' | 'resolved' | 'escalated';
          resolution_notes: string | null;
          resolved_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          patrol_id?: string | null;
          vehicle_record_id?: string | null;
          observation_id?: string | null;
          zone_id: string;
          breach_type: 'overstay' | 'no_self_contained' | 'no_wof' | 'consecutive_days' | 'unauthorized_zone' | 'nights_exceeded';
          breach_details: any;
          due_date?: string | null;
          notification_sent?: boolean;
          notification_method?: string | null;
          notified_at?: string | null;
          notified_by?: string | null;
          status?: 'pending' | 'notified' | 'resolved' | 'escalated';
          resolution_notes?: string | null;
          resolved_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<{
          id: string;
          organization_id: string;
          patrol_id: string | null;
          vehicle_record_id: string | null;
          observation_id: string | null;
          zone_id: string;
          breach_type: 'overstay' | 'no_self_contained' | 'no_wof' | 'consecutive_days' | 'unauthorized_zone' | 'nights_exceeded';
          breach_details: any;
          due_date: string | null;
          notification_sent: boolean;
          notification_method: string | null;
          notified_at: string | null;
          notified_by: string | null;
          status: 'pending' | 'notified' | 'resolved' | 'escalated';
          resolution_notes: string | null;
          resolved_at: string | null;
          created_at: string;
          updated_at: string;
        }>;
      };
      // ⚠️ vehicle_records DEPRECATED - Use vehicle_observations instead
      // This type is kept for backward compatibility only
      // All new code should use vehicle_observations
      health_safety_reports: {
        Row: {
          id: string;
          organization_id: string;
          zone_id: string;
          reported_by: string;
          patrol_id: string | null;
          details: string;
          severity: 'low' | 'medium' | 'high' | 'critical';
          status: 'pending' | 'under_review' | 'resolved';
          location_lat: number | null;
          location_lng: number | null;
          attachments: any;
          resolution_notes: string | null;
          resolved_by: string | null;
          resolved_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          zone_id: string;
          reported_by: string;
          patrol_id?: string | null;
          details: string;
          severity: 'low' | 'medium' | 'high' | 'critical';
          status?: 'pending' | 'under_review' | 'resolved';
          location_lat?: number | null;
          location_lng?: number | null;
          attachments?: any;
          resolution_notes?: string | null;
          resolved_by?: string | null;
          resolved_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<{
          id: string;
          organization_id: string;
          zone_id: string;
          reported_by: string;
          patrol_id: string | null;
          details: string;
          severity: 'low' | 'medium' | 'high' | 'critical';
          status: 'pending' | 'under_review' | 'resolved';
          location_lat: number | null;
          location_lng: number | null;
          attachments: any;
          resolution_notes: string | null;
          resolved_by: string | null;
          resolved_at: string | null;
          created_at: string;
          updated_at: string;
        }>;
      };
      incidents: {
        Row: {
          id: string;
          organization_id: string;
          user_id: string;
          zone_id: string;
          vehicle_id: string | null;
          enforcement_action_id: string | null;
          incident_type: string;
          description: string;
          status: 'pending' | 'investigating' | 'resolved' | 'closed' | 'open' | 'under_review';
          severity: 'low' | 'medium' | 'high' | 'critical';
          resolution_notes: string | null;
          resolved_by: string | null;
          location_lat: number | null;
          location_lng: number | null;
          attachments: string[];
          recorded_at: string;
          resolved_at: string | null;
          created_at: string;
          updated_at: string;
          photos: string[] | null;
          photo_hashes: string[] | null;
          photo_metadata_ids: string[] | null;
          gps_latitude: number | null;
          gps_longitude: number | null;
          gps_accuracy: number | null;
          happened_at: string | null;
          court_ready: boolean;
          approved_by: string | null;
          approved_at: string | null;
          evidence_notes: string | null;
          homeless_status: 'claimed' | 'confirmed' | 'none' | null;
          hs_issues: boolean;
          issue_detected: boolean;
          enforcement_required: boolean;
        };
        Insert: {
          id?: string;
          organization_id: string;
          user_id: string;
          zone_id: string;
          vehicle_id?: string | null;
          enforcement_action_id?: string | null;
          incident_type: string;
          description: string;
          status?: 'pending' | 'investigating' | 'resolved' | 'closed' | 'open' | 'under_review';
          severity?: 'low' | 'medium' | 'high' | 'critical';
          resolution_notes?: string | null;
          resolved_by?: string | null;
          location_lat?: number | null;
          location_lng?: number | null;
          attachments?: string[];
          recorded_at?: string;
          resolved_at?: string | null;
          created_at?: string;
          updated_at?: string;
          photos?: string[] | null;
          photo_hashes?: string[] | null;
          photo_metadata_ids?: string[] | null;
          gps_latitude?: number | null;
          gps_longitude?: number | null;
          gps_accuracy?: number | null;
          happened_at?: string | null;
          court_ready?: boolean;
          approved_by?: string | null;
          approved_at?: string | null;
          evidence_notes?: string | null;
          homeless_status?: 'claimed' | 'confirmed' | 'none' | null;
          hs_issues?: boolean;
          issue_detected?: boolean;
          enforcement_required?: boolean;
        };
        Update: Partial<{
          id: string;
          organization_id: string;
          user_id: string;
          zone_id: string;
          vehicle_id: string | null;
          enforcement_action_id: string | null;
          incident_type: string;
          description: string;
          status: 'pending' | 'investigating' | 'resolved' | 'closed' | 'open' | 'under_review';
          severity: 'low' | 'medium' | 'high' | 'critical';
          resolution_notes: string | null;
          resolved_by: string | null;
          location_lat: number | null;
          location_lng: number | null;
          attachments: string[];
          recorded_at: string;
          resolved_at: string | null;
          created_at: string;
          updated_at: string;
          photos: string[] | null;
          photo_hashes: string[] | null;
          photo_metadata_ids: string[] | null;
          gps_latitude: number | null;
          gps_longitude: number | null;
          gps_accuracy: number | null;
          happened_at: string | null;
          court_ready: boolean;
          approved_by: string | null;
          approved_at: string | null;
          evidence_notes: string | null;
          homeless_status: 'claimed' | 'confirmed' | 'none' | null;
          hs_issues: boolean;
          issue_detected: boolean;
          enforcement_required: boolean;
        }>;
      };
      user_profiles: {
        Row: {
          id: string;
          organization_id: string | null;
          first_name: string;
          last_name: string;
          email: string;
          role: string;
          phone: string | null;
          is_active: boolean;
          permissions: ('super_delete' | 'admin' | 'master' | 'officer')[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          organization_id?: string | null;
          first_name: string;
          last_name: string;
          email: string;
          role: string;
          phone?: string | null;
          is_active?: boolean;
          permissions?: ('super_delete' | 'admin' | 'master' | 'officer')[];
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<{
          id: string;
          organization_id: string | null;
          first_name: string;
          last_name: string;
          email: string;
          role: string;
          phone: string | null;
          is_active: boolean;
          permissions: ('super_delete' | 'admin' | 'master' | 'officer')[];
          created_at: string;
          updated_at: string;
        }>;
      };
      verification_results: {
        Row: {
          id: string;
          organization_id: string;
          vehicle_record_id: string;
          zone_id: string;
          patrol_id: string | null;
          verified_by: string;
          stayed_overnight: boolean;
          meets_requirements: boolean;
          days_stayed: number | null;
          consecutive_days: number | null;
          breach_detected: boolean;
          breach_type: string | null;
          verification_details: any;
          location_lat: number | null;
          location_lng: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          vehicle_record_id: string;
          zone_id: string;
          patrol_id?: string | null;
          verified_by: string;
          stayed_overnight: boolean;
          meets_requirements: boolean;
          days_stayed?: number | null;
          consecutive_days?: number | null;
          breach_detected?: boolean;
          breach_type?: string | null;
          verification_details?: any;
          location_lat?: number | null;
          location_lng?: number | null;
          created_at?: string;
        };
        Update: Partial<{
          id: string;
          organization_id: string;
          vehicle_record_id: string;
          zone_id: string;
          patrol_id: string | null;
          verified_by: string;
          stayed_overnight: boolean;
          meets_requirements: boolean;
          days_stayed: number | null;
          consecutive_days: number | null;
          breach_detected: boolean;
          breach_type: string | null;
          verification_details: any;
          location_lat: number | null;
          location_lng: number | null;
          created_at: string;
        }>;
      };
      audit_log: {
        Row: {
          id: string;
          organization_id: string | null;
          user_id: string | null;
          action: string;
          entity_type: string;
          entity_id: string | null;
          old_values: any;
          new_values: any;
          ip_address: string | null;
          user_agent: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id?: string | null;
          user_id?: string | null;
          action: string;
          entity_type: string;
          entity_id?: string | null;
          old_values?: any;
          new_values?: any;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Update: Partial<{
          id: string;
          organization_id: string | null;
          user_id: string | null;
          action: string;
          entity_type: string;
          entity_id: string | null;
          old_values: any;
          new_values: any;
          ip_address: string | null;
          user_agent: string | null;
          created_at: string;
        }>;
      };
      plate_history: {
        Row: {
          id: string;
          plate_number: string;
          zone_id: string;
          seen_at: string;
          location_lat: number | null;
          location_lng: number | null;
          recorded_by: string | null;
          patrol_id: string | null;
          stayed_overnight: boolean | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          plate_number: string;
          zone_id: string;
          seen_at: string;
          location_lat?: number | null;
          location_lng?: number | null;
          recorded_by?: string | null;
          patrol_id?: string | null;
          stayed_overnight?: boolean | null;
          created_at?: string;
        };
        Update: Partial<{
          id: string;
          plate_number: string;
          zone_id: string;
          seen_at: string;
          location_lat: number | null;
          location_lng: number | null;
          recorded_by: string | null;
          patrol_id: string | null;
          stayed_overnight: boolean | null;
          created_at: string;
        }>;
      };
      canonical_vehicles: {
        Row: {
          vehicle_id: string;
          plate_number: string;
          vehicle_make: string | null;
          vehicle_model: string | null;
          vehicle_color: string | null;
          first_seen_at: string;
          last_seen_at: string;
          total_observations: number;
          is_homeless: boolean;
          homeless_confirmed: boolean;
          homeless_confirmed_by: string | null;
          homeless_confirmed_at: string | null;
          homeless_notes: string | null;
          is_flagged: boolean;
          flagged_priority: string | null;
          flagged_reason: string | null;
          flagged_notes: string | null;
          flagged_at: string | null;
          flagged_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          vehicle_id?: string;
          plate_number: string;
          vehicle_make?: string | null;
          vehicle_model?: string | null;
          vehicle_color?: string | null;
          first_seen_at?: string;
          last_seen_at?: string;
          total_observations?: number;
          is_homeless?: boolean;
          homeless_confirmed?: boolean;
          homeless_confirmed_by?: string | null;
          homeless_confirmed_at?: string | null;
          homeless_notes?: string | null;
          is_flagged?: boolean;
          flagged_priority?: string | null;
          flagged_reason?: string | null;
          flagged_notes?: string | null;
          flagged_at?: string | null;
          flagged_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<{
          vehicle_id: string;
          plate_number: string;
          vehicle_make: string | null;
          vehicle_model: string | null;
          vehicle_color: string | null;
          first_seen_at: string;
          last_seen_at: string;
          total_observations: number;
          is_homeless: boolean;
          homeless_confirmed: boolean;
          homeless_confirmed_by: string | null;
          homeless_confirmed_at: string | null;
          homeless_notes: string | null;
          is_flagged: boolean;
          flagged_priority: string | null;
          flagged_reason: string | null;
          flagged_notes: string | null;
          flagged_at: string | null;
          flagged_by: string | null;
          created_at: string;
          updated_at: string;
        }>;
      };
      vehicle_observations: {
        Row: {
          observation_id: string;
          vehicle_id: string;
          organization_id: string | null;
          zone_id: string;
          recorded_by: string | null;
          recorded_at: string;
          source_type: 'patrol' | 'scan' | 'import' | 'migration' | null;
          is_self_contained: boolean;
          is_compliant: boolean;
          gps_latitude: number | null;
          gps_longitude: number | null;
          gps_accuracy: number | null;
          evidence_photos: any;
          notes: string | null;
          original_record_id: string | null;
          created_at: string;
          // Enhanced fields from vehicle_records consolidation
          vehicle_make: string | null;
          vehicle_model: string | null;
          vehicle_color: string | null;
          vehicle_year: string | null;
          plate_input_method: string | null;
          homeless_claimed: boolean;
          homeless_confirmed: boolean;
          homeless_confirmed_by: string | null;
          homeless_confirmed_at: string | null;
          behavioral_flags: any;
          requires_followup: boolean;
          followup_reason: string | null;
          followup_priority: 'low' | 'medium' | 'high' | 'urgent' | null;
          followup_resolved: boolean;
          followup_resolved_by: string | null;
          followup_resolved_at: string | null;
          followup_resolution_notes: string | null;
          incident_id: string | null;
          investigation_job_id: string | null;
          health_safety_report_id: string | null;
          weather_conditions: string | null;
          photo_hashes: string[] | null;
          photo_metadata_ids: string[] | null;
          compliance_checked_at: string | null;
          compliance_matrix_version: number | null;
          evidence_timestamp: string;
        };
        Insert: {
          observation_id?: string;
          vehicle_id: string;
          organization_id?: string | null;
          zone_id: string;
          recorded_by?: string | null;
          recorded_at?: string;
          source_type?: 'patrol' | 'scan' | 'import' | 'migration' | null;
          is_self_contained?: boolean;
          is_compliant?: boolean;
          gps_latitude?: number | null;
          gps_longitude?: number | null;
          gps_accuracy?: number | null;
          evidence_photos?: any;
          notes?: string | null;
          original_record_id?: string | null;
          created_at?: string;
          vehicle_make?: string | null;
          vehicle_model?: string | null;
          vehicle_color?: string | null;
          vehicle_year?: string | null;
          plate_input_method?: string | null;
          homeless_claimed?: boolean;
          homeless_confirmed?: boolean;
          homeless_confirmed_by?: string | null;
          homeless_confirmed_at?: string | null;
          behavioral_flags?: any;
          requires_followup?: boolean;
          followup_reason?: string | null;
          followup_priority?: 'low' | 'medium' | 'high' | 'urgent' | null;
          followup_resolved?: boolean;
          followup_resolved_by?: string | null;
          followup_resolved_at?: string | null;
          followup_resolution_notes?: string | null;
          incident_id?: string | null;
          investigation_job_id?: string | null;
          health_safety_report_id?: string | null;
          weather_conditions?: string | null;
          photo_hashes?: string[] | null;
          photo_metadata_ids?: string[] | null;
          compliance_checked_at?: string | null;
          compliance_matrix_version?: number | null;
          evidence_timestamp?: string;
        };
        Update: Partial<{
          observation_id: string;
          vehicle_id: string;
          organization_id: string | null;
          zone_id: string;
          recorded_by: string | null;
          recorded_at: string;
          source_type: 'patrol' | 'scan' | 'import' | 'migration' | null;
          is_self_contained: boolean;
          is_compliant: boolean;
          gps_latitude: number | null;
          gps_longitude: number | null;
          gps_accuracy: number | null;
          evidence_photos: any;
          notes: string | null;
          original_record_id: string | null;
          created_at: string;
          vehicle_make: string | null;
          vehicle_model: string | null;
          vehicle_color: string | null;
          vehicle_year: string | null;
          plate_input_method: string | null;
          homeless_claimed: boolean;
          homeless_confirmed: boolean;
          homeless_confirmed_by: string | null;
          homeless_confirmed_at: string | null;
          behavioral_flags: any;
          requires_followup: boolean;
          followup_reason: string | null;
          followup_priority: 'low' | 'medium' | 'high' | 'urgent' | null;
          followup_resolved: boolean;
          followup_resolved_by: string | null;
          followup_resolved_at: string | null;
          followup_resolution_notes: string | null;
          incident_id: string | null;
          investigation_job_id: string | null;
          health_safety_report_id: string | null;
          weather_conditions: string | null;
          photo_hashes: string[] | null;
          photo_metadata_ids: string[] | null;
          compliance_checked_at: string | null;
          compliance_matrix_version: number | null;
          evidence_timestamp: string;
        }>;
      };
      compliance_results: {
        Row: {
          id: string;
          observation_id: string | null;
          vehicle_id: string | null;
          zone_id: string;
          organization_id: string | null;
          matrix_id: string | null;
          matrix_version: number | null;
          is_compliant: boolean;
          violation_reasons: string[];
          metrics_json: any;
          matrix_snapshot: any;
          evaluated_at: string;
          created_at: string;
          // GPS-verified fields
          after_hours_violation: boolean | null;
          stay_confirmed_by_gps: boolean | null;
          gps_verified_consecutive_nights: number | null;
          gps_evidence_json: any;
        };
        Insert: {
          id?: string;
          observation_id?: string | null;
          vehicle_id?: string | null;
          zone_id: string;
          organization_id?: string | null;
          matrix_id?: string | null;
          matrix_version?: number | null;
          is_compliant: boolean;
          violation_reasons?: string[];
          metrics_json?: any;
          matrix_snapshot: any;
          evaluated_at?: string;
          created_at?: string;
          after_hours_violation?: boolean | null;
          stay_confirmed_by_gps?: boolean | null;
          gps_verified_consecutive_nights?: number | null;
          gps_evidence_json?: any;
        };
        Update: Partial<{
          id: string;
          observation_id: string | null;
          vehicle_id: string | null;
          zone_id: string;
          organization_id: string | null;
          matrix_id: string | null;
          matrix_version: number | null;
          is_compliant: boolean;
          violation_reasons: string[];
          metrics_json: any;
          matrix_snapshot: any;
          evaluated_at: string;
          created_at: string;
          after_hours_violation: boolean | null;
          stay_confirmed_by_gps: boolean | null;
          gps_verified_consecutive_nights: number | null;
          gps_evidence_json: any;
        }>;
      };
      zone_compliance_matrix: {
        Row: {
          id: string;
          zone_id: string;
          organization_id: string;
          version: number;
          effective_from: string;
          effective_to: string | null;
          self_contained_required: boolean;
          nights_per_month: number;
          max_consecutive_nights: number;
          day_visit_only: boolean;
          allowed_days: any;
          homeless_exemption: boolean;
          created_by: string | null;
          change_reason: string | null;
          change_notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          zone_id: string;
          organization_id: string;
          version: number;
          effective_from?: string;
          effective_to?: string | null;
          self_contained_required?: boolean;
          nights_per_month?: number;
          max_consecutive_nights?: number;
          day_visit_only?: boolean;
          allowed_days?: any;
          homeless_exemption?: boolean;
          created_by?: string | null;
          change_reason?: string | null;
          change_notes?: string | null;
          created_at?: string;
        };
        Update: Partial<{
          id: string;
          zone_id: string;
          organization_id: string;
          version: number;
          effective_from: string;
          effective_to: string | null;
          self_contained_required: boolean;
          nights_per_month: number;
          max_consecutive_nights: number;
          day_visit_only: boolean;
          allowed_days: any;
          homeless_exemption: boolean;
          created_by: string | null;
          change_reason: string | null;
          change_notes: string | null;
          created_at: string;
        }>;
      };
      drift_events: {
        Row: {
          id: string;
          zone_id: string;
          organization_id: string;
          matrix_version_from: number | null;
          matrix_version_to: number | null;
          matrix_id_from: string | null;
          matrix_id_to: string | null;
          observations_affected: number;
          compliance_changed: number;
          criteria_changed: any;
          detected_at: string;
          detected_by: string | null;
          status: 'pending' | 'reviewed' | 'resolved';
          remediation_notes: string | null;
          reviewed_at: string | null;
          reviewed_by: string | null;
        };
        Insert: {
          id?: string;
          zone_id: string;
          organization_id: string;
          matrix_version_from?: number | null;
          matrix_version_to?: number | null;
          matrix_id_from?: string | null;
          matrix_id_to?: string | null;
          observations_affected?: number;
          compliance_changed?: number;
          criteria_changed?: any;
          detected_at?: string;
          detected_by?: string | null;
          status?: 'pending' | 'reviewed' | 'resolved';
          remediation_notes?: string | null;
          reviewed_at?: string | null;
          reviewed_by?: string | null;
        };
        Update: Partial<{
          id: string;
          zone_id: string;
          organization_id: string;
          matrix_version_from: number | null;
          matrix_version_to: number | null;
          matrix_id_from: string | null;
          matrix_id_to: string | null;
          observations_affected: number;
          compliance_changed: number;
          criteria_changed: any;
          detected_at: string;
          detected_by: string | null;
          status: 'pending' | 'reviewed' | 'resolved';
          remediation_notes: string | null;
          reviewed_at: string | null;
          reviewed_by: string | null;
        }>;
      };
      admin_recalculation_actions: {
        Row: {
          id: string;
          scope_type: 'ZONE' | 'ORG' | 'BUILD';
          target_zone_ids: string[] | null;
          target_org_ids: string[] | null;
          date_range_start: string | null;
          date_range_end: string | null;
          observations_processed: number;
          compliance_changed: number;
          drift_events_created: number;
          status: 'running' | 'completed' | 'failed';
          error_message: string | null;
          performed_by: string | null;
          performed_at: string;
          completed_at: string | null;
          duration_seconds: number | null;
        };
        Insert: {
          id?: string;
          scope_type: 'ZONE' | 'ORG' | 'BUILD';
          target_zone_ids?: string[] | null;
          target_org_ids?: string[] | null;
          date_range_start?: string | null;
          date_range_end?: string | null;
          observations_processed?: number;
          compliance_changed?: number;
          drift_events_created?: number;
          status?: 'running' | 'completed' | 'failed';
          error_message?: string | null;
          performed_by?: string | null;
          performed_at?: string;
          completed_at?: string | null;
          duration_seconds?: number | null;
        };
        Update: Partial<{
          id: string;
          scope_type: 'ZONE' | 'ORG' | 'BUILD';
          target_zone_ids: string[] | null;
          target_org_ids: string[] | null;
          date_range_start: string | null;
          date_range_end: string | null;
          observations_processed: number;
          compliance_changed: number;
          drift_events_created: number;
          status: 'running' | 'completed' | 'failed';
          error_message: string | null;
          performed_by: string | null;
          performed_at: string;
          completed_at: string | null;
          duration_seconds: number | null;
        }>;
      };
      photo_metadata: {
        Row: {
          id: string;
          photo_url: string;
          file_name: string;
          bucket_name: string;
          storage_path: string;
          photo_hash: string;
          photo_type: 'full' | 'cropped' | 'evidence';
          file_size_bytes: number | null;
          width: number | null;
          height: number | null;
          mime_type: string | null;
          organization_id: string | null;
          user_id: string | null;
          incident_id: string | null;
          vehicle_record_id: string | null;
          observation_id: string | null;
          retention_policy: string;
          court_ready: boolean;
          delete_after_days: number;
          scheduled_deletion_at: string | null;
          gps_latitude: number | null;
          gps_longitude: number | null;
          gps_accuracy: number | null;
          captured_at: string;
          uploaded_at: string;
          created_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          photo_url: string;
          file_name: string;
          bucket_name: string;
          storage_path: string;
          photo_hash: string;
          photo_type: 'full' | 'cropped' | 'evidence';
          file_size_bytes?: number | null;
          width?: number | null;
          height?: number | null;
          mime_type?: string | null;
          organization_id?: string | null;
          user_id?: string | null;
          incident_id?: string | null;
          vehicle_record_id?: string | null;
          observation_id?: string | null;
          retention_policy?: string;
          court_ready?: boolean;
          delete_after_days?: number;
          scheduled_deletion_at?: string | null;
          gps_latitude?: number | null;
          gps_longitude?: number | null;
          gps_accuracy?: number | null;
          captured_at?: string;
          uploaded_at?: string;
          created_at?: string;
          deleted_at?: string | null;
        };
        Update: Partial<{
          id: string;
          photo_url: string;
          file_name: string;
          bucket_name: string;
          storage_path: string;
          photo_hash: string;
          photo_type: 'full' | 'cropped' | 'evidence';
          file_size_bytes: number | null;
          width: number | null;
          height: number | null;
          mime_type: string | null;
          organization_id: string | null;
          user_id: string | null;
          incident_id: string | null;
          vehicle_record_id: string | null;
          observation_id: string | null;
          retention_policy: string;
          court_ready: boolean;
          delete_after_days: number;
          scheduled_deletion_at: string | null;
          gps_latitude: number | null;
          gps_longitude: number | null;
          gps_accuracy: number | null;
          captured_at: string;
          uploaded_at: string;
          created_at: string;
          deleted_at: string | null;
        }>;
      };
      plate_scans: {
        Row: {
          id: string;
          organization_id: string;
          zone_id: string;
          scanned_by: string;
          plate_number: string;
          scan_mode: 'handheld' | 'driving';
          scanned_photo: string | null;
          confidence_score: number | null;
          gps_latitude: number | null;
          gps_longitude: number | null;
          gps_accuracy: number | null;
          ai_vehicle_make: string | null;
          ai_vehicle_model: string | null;
          ai_vehicle_color: string | null;
          ai_likely_self_contained: boolean;
          ai_detected_stickers: any;
          reviewed: boolean;
          reviewed_by: string | null;
          reviewed_at: string | null;
          review_notes: string | null;
          review_action: 'approved' | 'rejected' | 'needs_followup' | null;
          flagged_vehicle_detected: boolean;
          breach_detected: boolean;
          violation_summary: string | null;
          vehicle_record_id: string | null;
          converted_to_record: boolean;
          scanned_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          zone_id: string;
          scanned_by: string;
          plate_number: string;
          scan_mode: 'handheld' | 'driving';
          scanned_photo?: string | null;
          confidence_score?: number | null;
          gps_latitude?: number | null;
          gps_longitude?: number | null;
          gps_accuracy?: number | null;
          ai_vehicle_make?: string | null;
          ai_vehicle_model?: string | null;
          ai_vehicle_color?: string | null;
          ai_likely_self_contained?: boolean;
          ai_detected_stickers?: any;
          reviewed?: boolean;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          review_notes?: string | null;
          review_action?: 'approved' | 'rejected' | 'needs_followup' | null;
          flagged_vehicle_detected?: boolean;
          breach_detected?: boolean;
          violation_summary?: string | null;
          vehicle_record_id?: string | null;
          converted_to_record?: boolean;
          scanned_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<{
          id: string;
          organization_id: string;
          zone_id: string;
          scanned_by: string;
          plate_number: string;
          scan_mode: 'handheld' | 'driving';
          scanned_photo: string | null;
          confidence_score: number | null;
          gps_latitude: number | null;
          gps_longitude: number | null;
          gps_accuracy: number | null;
          ai_vehicle_make: string | null;
          ai_vehicle_model: string | null;
          ai_vehicle_color: string | null;
          ai_likely_self_contained: boolean;
          ai_detected_stickers: any;
          reviewed: boolean;
          reviewed_by: string | null;
          reviewed_at: string | null;
          review_notes: string | null;
          review_action: 'approved' | 'rejected' | 'needs_followup' | null;
          flagged_vehicle_detected: boolean;
          breach_detected: boolean;
          violation_summary: string | null;
          vehicle_record_id: string | null;
          converted_to_record: boolean;
          scanned_at: string;
          created_at: string;
          updated_at: string;
        }>;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
  };
};
