#!/usr/bin/env node

import fs from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';
import { buildCanonicalTrainingSources } from './bob-training-sources.mjs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const workspaceRoot = path.resolve(__dirname, '..');
const outputPath = path.join(workspaceRoot, 'docs', 'BOB_BRAIN_DUMP.md');
const maxOutputBytes = Number(process.env.BOB_BRAIN_DUMP_MAX_BYTES || 90 * 1024 * 1024);

const preferredSources = buildCanonicalTrainingSources(workspaceRoot, { includeContext: true });

function toAbsolute(relativePath) {
  return path.join(workspaceRoot, relativePath);
}

async function pathExists(filePath) {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function collectFiles(relativePath) {
  const absolutePath = toAbsolute(relativePath);
  if (!(await pathExists(absolutePath))) return [];

  const stat = await fs.stat(absolutePath);
  if (stat.isFile()) return [relativePath];
  if (!stat.isDirectory()) return [];

  const files = [];
  const entries = await fs.readdir(absolutePath, { withFileTypes: true });
  entries.sort((left, right) => left.name.localeCompare(right.name));

  for (const entry of entries) {
    const childRelative = path.posix.join(relativePath.replace(/\\/g, '/'), entry.name);
    const childAbsolute = toAbsolute(childRelative);
    if (entry.isDirectory()) {
      const nested = await collectFiles(childRelative);
      files.push(...nested);
      continue;
    }
    if (entry.isFile()) {
      const childStat = await fs.stat(childAbsolute);
      if (childStat.size <= 1024 * 1024) files.push(childRelative);
    }
  }

  return files;
}

async function main() {
  const collected = [];
  const seen = new Set();

  for (const source of preferredSources) {
    for (const filePath of await collectFiles(source)) {
      if (seen.has(filePath)) continue;
      seen.add(filePath);
      collected.push(filePath);
    }
  }

  const sections = [
    '# PROJECT TRUTH SOURCE',
    '',
    `Generated at: ${new Date().toISOString()}`,
    `Workspace root: ${workspaceRoot}`,
    `Max output bytes: ${maxOutputBytes}`,
    '',
    'This file is generated by scripts/auto-ingest.mjs and is intended to be the living architecture context Bob reads first.',
    '',
  ];

  const skippedForSize = [];
  let output = `${sections.join('\n')}\n`;

  for (const relativePath of collected) {
    const absolutePath = toAbsolute(relativePath);
    const content = await fs.readFile(absolutePath, 'utf8');

    const fileSection = [
      `## FILE: ${relativePath}`,
      '',
      '```',
      content.trimEnd(),
      '```',
      '',
    ].join('\n');

    if (Buffer.byteLength(output, 'utf8') + Buffer.byteLength(fileSection, 'utf8') > maxOutputBytes) {
      skippedForSize.push(relativePath);
      continue;
    }

    output += fileSection;
  }

  if (skippedForSize.length > 0) {
    const truncationSection = [
      '## TRUNCATION NOTICE',
      '',
      `Skipped ${skippedForSize.length} files to keep docs/BOB_BRAIN_DUMP.md under ${maxOutputBytes} bytes.`,
      '',
      ...skippedForSize.slice(0, 50).map((filePath) => `- ${filePath}`),
      ...(skippedForSize.length > 50 ? [`- ...and ${skippedForSize.length - 50} more`] : []),
      '',
    ].join('\n');

    if (Buffer.byteLength(output, 'utf8') + Buffer.byteLength(truncationSection, 'utf8') <= maxOutputBytes) {
      output += truncationSection;
    }
  }

  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.writeFile(outputPath, output, 'utf8');
  console.log(`Bob brain dump updated: ${path.relative(workspaceRoot, outputPath)}`);
  console.log(`Files ingested: ${collected.length}`);
  if (skippedForSize.length > 0) {
    console.log(`Files skipped for size: ${skippedForSize.length}`);
  }
  console.log(`Final size (bytes): ${Buffer.byteLength(output, 'utf8')}`);
}

main().catch((error) => {
  console.error(error?.message || String(error));
  process.exit(1);
});