#!/usr/bin/env node

import fs from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const workspaceRoot = path.resolve(__dirname, '..');
const outputPath = path.join(workspaceRoot, 'docs', 'BOB_BRAIN_DUMP.md');

const preferredSources = [
  'docs/architecture-drivers',
  'docs/architecture',
  'docs/DECISIONS.md',
  'docs/LESSONS_LEARNED.md',
  'docs/adr',
  'docs/BOB_FAILURE_SUMMARY.md',
  'docs/BOB_AUTONOMOUS_LEARNING.md',
  'docs/BOB_FIELD_INTELLIGENCE.md',
  'docs/BOB_TRAINING_TRUTH_PROTOCOL.md',
  'docs/rules',
  'docs/templates/clients',
  'docs/BOB_TRAINING_ADVANCED_ARCHITECT_2026.md',
  'data/client-geofence-registry.json',
  'data/roster-active-shifts.json',
  'scripts/spatial-intelligence-engine.mjs',
  'scripts/import-client-geofences.mjs',
  'scripts/roster-context-adapter.mjs',
  'scripts/spatial-context-api.mjs',
  'src/modules',
  'package.json',
  'system_state.json',
  '.github/copilot-instructions.md',
];

function toAbsolute(relativePath) {
  return path.join(workspaceRoot, relativePath);
}

async function pathExists(filePath) {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function collectFiles(relativePath) {
  const absolutePath = toAbsolute(relativePath);
  if (!(await pathExists(absolutePath))) return [];

  const stat = await fs.stat(absolutePath);
  if (stat.isFile()) return [relativePath];
  if (!stat.isDirectory()) return [];

  const files = [];
  const entries = await fs.readdir(absolutePath, { withFileTypes: true });
  entries.sort((left, right) => left.name.localeCompare(right.name));

  for (const entry of entries) {
    const childRelative = path.posix.join(relativePath.replace(/\\/g, '/'), entry.name);
    const childAbsolute = toAbsolute(childRelative);
    if (entry.isDirectory()) {
      const nested = await collectFiles(childRelative);
      files.push(...nested);
      continue;
    }
    if (entry.isFile()) {
      const childStat = await fs.stat(childAbsolute);
      if (childStat.size <= 1024 * 1024) files.push(childRelative);
    }
  }

  return files;
}

async function main() {
  const collected = [];
  const seen = new Set();

  for (const source of preferredSources) {
    for (const filePath of await collectFiles(source)) {
      if (seen.has(filePath)) continue;
      seen.add(filePath);
      collected.push(filePath);
    }
  }

  const sections = [
    '# PROJECT TRUTH SOURCE',
    '',
    `Generated at: ${new Date().toISOString()}`,
    `Workspace root: ${workspaceRoot}`,
    '',
    'This file is generated by scripts/auto-ingest.mjs and is intended to be the living architecture context Bob reads first.',
    '',
  ];

  for (const relativePath of collected) {
    const absolutePath = toAbsolute(relativePath);
    const content = await fs.readFile(absolutePath, 'utf8');
    sections.push(`## FILE: ${relativePath}`);
    sections.push('');
    sections.push('```');
    sections.push(content.trimEnd());
    sections.push('```');
    sections.push('');
  }

  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.writeFile(outputPath, `${sections.join('\n')}\n`, 'utf8');
  console.log(`Bob brain dump updated: ${path.relative(workspaceRoot, outputPath)}`);
  console.log(`Files ingested: ${collected.length}`);
}

main().catch((error) => {
  console.error(error?.message || String(error));
  process.exit(1);
});