#!/bin/bash
set -e

# Bob mode switcher
# Usage:
#   bash scripts/bob-set-mode.sh LOGIC_STRICT
#   bash scripts/bob-set-mode.sh BRIDGE_WIT
#   bash scripts/bob-set-mode.sh VOICE_SNAPPY
#   bash scripts/bob-set-mode.sh SAFETY_LOCK

MODE_RAW="${1:-LOGIC_STRICT}"
MODE=$(echo "$MODE_RAW" | tr '[:lower:]' '[:upper:]')

case "$MODE" in
  LOGIC_STRICT|BRIDGE_WIT|VOICE_SNAPPY|SAFETY_LOCK)
    ;;
  *)
    echo "Invalid mode: $MODE_RAW"
    echo "Valid modes: LOGIC_STRICT | BRIDGE_WIT | VOICE_SNAPPY | SAFETY_LOCK"
    exit 2
    ;;
esac

REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
RUNTIME_DIR="$REPO_ROOT/.runtime"
MODE_FILE="$RUNTIME_DIR/bob-mode.env"

mkdir -p "$RUNTIME_DIR"

cat > "$MODE_FILE" << EOF
# Auto-generated by scripts/bob-set-mode.sh
export BOB_PERSONA_MODE="$MODE"

# Derived behavior flags
export BOB_WIT_ENABLED="$([ "$MODE" = "BRIDGE_WIT" ] && echo 1 || echo 0)"
export BOB_VOICE_SNAPPY="$([ "$MODE" = "VOICE_SNAPPY" ] && echo 1 || echo 0)"
export BOB_SAFETY_LOCK="$([ "$MODE" = "SAFETY_LOCK" ] && echo 1 || echo 0)"
EOF

echo "Mode set: $MODE"
echo "Wrote: $MODE_FILE"
echo ""
echo "Load it in current shell:"
echo "  source .runtime/bob-mode.env"
echo ""
echo "Current behavior:"
if [ "$MODE" = "LOGIC_STRICT" ]; then
  echo "- Direct, technical, no playful tone"
  echo "- Preferred for release/security workflows"
elif [ "$MODE" = "BRIDGE_WIT" ]; then
  echo "- Dry wit enabled, still precise and professional"
  echo "- Not for incident/severity-critical tasks"
elif [ "$MODE" = "VOICE_SNAPPY" ]; then
  echo "- Short spoken responses, anchor phrases enabled"
  echo "- Optimized for real-time voice interactions"
else
  echo "- Safety-first mode, sarcasm disabled"
  echo "- Risk-first framing and conservative output"
fi
