export type AppShell = 'officer' | 'admin' | 'master' | 'shared'

export type AppRole =
  | 'master'
  | 'admin'
  | 'officer'
  | 'admin_officer'
  | 'nzscv_monitor'
  | 'grand_master'
  | 'client_viewer'

export type VisibilityMode = 'production' | 'internal' | 'hidden'

export type PreloadPolicy = 'none' | 'intent' | 'viewport' | 'eager'

export interface RouteManifestEntry {
  routeId: string
  path: string
  shell: AppShell
  rolesAllowed: AppRole[]
  permissionArea?: string | null
  navGroup?: string | null
  navLabel?: string | null
  visibilityMode: VisibilityMode
  featureFlag?: string | null
  mobilePriority?: number | null
  preloadPolicy: PreloadPolicy
}

export const ROUTE_MANIFEST_VERSION = '2026-04-23.v2'

// Phase 1 seed manifest: only high-traffic primary routes.
// All canonical routes are now active. Legacy aliases exist only as backward-compatibility redirects.
export const routeManifest: RouteManifestEntry[] = [
  {
    routeId: 'auth.login',
    path: '/login',
    shell: 'shared',
    rolesAllowed: ['master', 'admin', 'officer', 'admin_officer', 'nzscv_monitor', 'grand_master', 'client_viewer'],
    navGroup: null,
    navLabel: null,
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: null,
    preloadPolicy: 'eager',
  },
  {
    routeId: 'root.admin-hub',
    path: '/',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Core',
    navLabel: 'Admin Hub',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 1,
    preloadPolicy: 'intent',
  },
  {
    routeId: 'portal.selection',
    path: '/portal-selection',
    shell: 'shared',
    rolesAllowed: ['admin_officer'],
    navGroup: null,
    navLabel: null,
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  {
    routeId: 'officer.home',
    path: '/officer-home',
    shell: 'officer',
    rolesAllowed: ['officer', 'admin_officer'],
    navGroup: 'Officer',
    navLabel: 'Officer Home',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 1,
    preloadPolicy: 'intent',
  },
  {
    routeId: 'officer.field',
    path: '/field-officer',
    shell: 'officer',
    rolesAllowed: ['officer', 'admin_officer'],
    permissionArea: 'field_officer',
    navGroup: 'Officer',
    navLabel: 'Field Officer',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 1,
    preloadPolicy: 'intent',
  },
  {
    routeId: 'admin.dashboard',
    path: '/admin/dashboard',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Management',
    navLabel: 'Ops Dashboard',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'intent',
  },
  {
    routeId: 'admin.compliance',
    path: '/compliance',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Operations',
    navLabel: 'Compliance Hub',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'intent',
  },
  {
    routeId: 'admin.observation-records',
    path: '/observation-records',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master', 'officer'],
    navGroup: 'Operations',
    navLabel: 'Observations',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'intent',
  },
  {
    routeId: 'admin.observations-report',
    path: '/observations-report',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Operations',
    navLabel: 'Observations Report',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.breaches',
    path: '/breaches',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master', 'officer'],
    navGroup: 'Operations',
    navLabel: 'Breaches',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'intent',
  },
  {
    routeId: 'admin.breach-notices',
    path: '/breach-notices',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master', 'officer'],
    navGroup: 'Operations',
    navLabel: 'Breach Notices',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.enforcement-actions',
    path: '/enforcement-actions',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master', 'officer'],
    navGroup: 'Operations',
    navLabel: 'Enforcement Actions',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.enforcement-review',
    path: '/enforcement-review',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Operations',
    navLabel: 'Enforcement Review',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.enforcement-command-center',
    path: '/enforcement-command-center',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Operations',
    navLabel: 'Enforcement Console',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'intent',
  },
  {
    routeId: 'admin.disputes',
    path: '/disputes',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Operations',
    navLabel: 'Disputes',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.notice-to-vacate',
    path: '/notice-to-vacate',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Operations',
    navLabel: 'Notice to Vacate',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.discrepancies',
    path: '/admin/discrepancies',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Operations',
    navLabel: 'Discrepancies',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.infringements',
    path: '/infringements',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master', 'officer'],
    navGroup: 'Operations',
    navLabel: 'Infringements',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.compliance-analytics',
    path: '/compliance-analytics',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Operations',
    navLabel: 'Compliance Analytics',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.patrol-checkpoints',
    path: '/patrol-checkpoints',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Operations',
    navLabel: 'Checkpoints',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.patrol-schedule',
    path: '/patrol-schedule',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Operations',
    navLabel: 'Patrol Schedule',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.patrol-kpis',
    path: '/patrol-kpis',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Operations',
    navLabel: 'Patrol KPIs',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.vehicles',
    path: '/vehicles',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master', 'officer'],
    navGroup: 'Management',
    navLabel: 'Vehicles',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'intent',
  },
  {
    routeId: 'admin.vehicle-registry',
    path: '/vehicle-registry',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master', 'nzscv_monitor'],
    navGroup: 'Management',
    navLabel: 'Vehicle Registry',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'intent',
  },
  {
    routeId: 'admin.nzscv-monitor',
    path: '/admin/nzscv',
    shell: 'admin',
    rolesAllowed: ['admin', 'master', 'grand_master', 'nzscv_monitor'],
    navGroup: 'Management',
    navLabel: 'NZSCV Monitor',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.canonical-records',
    path: '/admin/canonical-records',
    shell: 'admin',
    rolesAllowed: ['admin', 'master', 'grand_master'],
    navGroup: 'Management',
    navLabel: 'Canonical Records',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.zones',
    path: '/zones',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Management',
    navLabel: 'Zones',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'intent',
  },
  {
    routeId: 'admin.client-master-list',
    path: '/client-master-list',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Management',
    navLabel: 'Client Master List',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.client-sites',
    path: '/client-sites',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Management',
    navLabel: 'Client Sites',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.site-permissions',
    path: '/site-permissions',
    shell: 'admin',
    rolesAllowed: ['admin', 'master', 'grand_master'],
    navGroup: 'Management',
    navLabel: 'Site Permissions',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.crm',
    path: '/crm',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Management',
    navLabel: 'CRM / Accounts',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.tender-workspace',
    path: '/tender-workspace',
    shell: 'admin',
    rolesAllowed: ['admin', 'master', 'grand_master'],
    navGroup: 'Management',
    navLabel: 'Tenders & Contracts',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.tender-reference-library',
    path: '/tender-reference-library',
    shell: 'admin',
    rolesAllowed: ['admin', 'master', 'grand_master'],
    navGroup: 'Management',
    navLabel: 'Reference Library',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.pricing',
    path: '/pricing',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Management',
    navLabel: 'Service Pricing',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.invoicing',
    path: '/invoicing',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Management',
    navLabel: 'Invoicing',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.users',
    path: '/users',
    shell: 'admin',
    rolesAllowed: ['admin', 'master', 'grand_master'],
    navGroup: 'Management',
    navLabel: 'Users',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.organization-profile',
    path: '/organization-profile',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Management',
    navLabel: 'Organisation',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'master.organizations',
    path: '/organizations',
    shell: 'master',
    rolesAllowed: ['master', 'grand_master'],
    navGroup: 'Management',
    navLabel: 'Organisations',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.hotspots',
    path: '/hotspots',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Live Ops',
    navLabel: 'Hotspots Map',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.reports',
    path: '/reports',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Records',
    navLabel: 'Reports',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'intent',
  },
  {
    routeId: 'admin.incidents',
    path: '/incidents',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master', 'officer'],
    navGroup: 'Records',
    navLabel: 'Incidents & Evidence',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'intent',
  },
  {
    routeId: 'admin.incident-reports',
    path: '/incident-reports',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Records',
    navLabel: 'Incident Reports',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.investigations',
    path: '/investigations',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Records',
    navLabel: 'Investigations',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.person-records',
    path: '/person-records',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Records',
    navLabel: 'Person Records',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.reports-hub',
    path: '/reports-hub',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Records',
    navLabel: 'Reports Hub',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'intent',
  },
  {
    routeId: 'admin.audit-log',
    path: '/audit-log',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Records',
    navLabel: 'Audit Log',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.privacy-curtain',
    path: '/privacy-curtain',
    shell: 'admin',
    rolesAllowed: ['admin', 'master', 'grand_master'],
    navGroup: 'Records',
    navLabel: 'Privacy Curtain',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.observations-map',
    path: '/observations',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Records',
    navLabel: 'Observation Map',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.ai-analysis',
    path: '/ai-analysis',
    shell: 'admin',
    rolesAllowed: ['admin', 'master', 'grand_master'],
    navGroup: 'Bob',
    navLabel: 'Bob Analysis',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.live-tracking',
    path: '/live-tracking',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Live Ops',
    navLabel: 'Live Tracking',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'intent',
  },
  {
    routeId: 'admin.live-patrol',
    path: '/live-patrol',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Live Ops',
    navLabel: 'Live Patrol Monitor',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'intent',
  },
  {
    routeId: 'admin.operations-map',
    path: '/operations-map',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Live Ops',
    navLabel: 'Operations Map',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.dispatch',
    path: '/dispatch',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Live Ops',
    navLabel: 'Dispatch Console',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.dispatch-monitor',
    path: '/dispatch-monitor',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Live Ops',
    navLabel: 'Dispatch Monitor',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.dispatch-wizard',
    path: '/dispatch-wizard',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Live Ops',
    navLabel: 'Dispatch Wizard',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.dispatched-jobs',
    path: '/dispatched-jobs',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Live Ops',
    navLabel: 'Dispatched Jobs',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.team-chat',
    path: '/team-chat',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master', 'officer'],
    navGroup: 'Live Ops',
    navLabel: 'Team Chat',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.radio',
    path: '/radio',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master', 'officer'],
    navGroup: 'Live Ops',
    navLabel: 'Radio',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.noise-control',
    path: '/noise-control',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Specialist Portals',
    navLabel: 'Noise Control',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.biosecurity-control',
    path: '/biosecurity-control',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Specialist Portals',
    navLabel: 'Biosecurity (CNG)',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.smoke-control',
    path: '/smoke-control',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Specialist Portals',
    navLabel: 'Smoke Complaints (OOH)',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.parking',
    path: '/parking',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Specialist Portals',
    navLabel: 'Parking Enforcement',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.officer-welfare',
    path: '/officer-welfare',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Specialist Portals',
    navLabel: 'Officer Welfare',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.identity-verification',
    path: '/identity-verification',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Specialist Portals',
    navLabel: 'ID Verification',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.parking-officer',
    path: '/parking-officer',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Specialist Services',
    navLabel: 'Parking Officer',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.noise-officer',
    path: '/noise-officer',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Specialist Services',
    navLabel: 'Noise Officer',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.compliance-dashboard',
    path: '/compliance-dashboard',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Compliance',
    navLabel: 'Compliance Dashboard',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'intent',
  },
  {
    routeId: 'admin.face-recognition',
    path: '/face-recognition',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'People & Incidents',
    navLabel: 'Face Recognition',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.points-of-interest',
    path: '/points-of-interest',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'People & Incidents',
    navLabel: 'Points of Interest',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.site-risk-assessment',
    path: '/site-risk-assessment',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'People & Incidents',
    navLabel: 'Site Risk Assessment',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.roster',
    path: '/roster',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Roster & Workforce',
    navLabel: 'Roster Planner',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.open-shifts',
    path: '/open-shifts',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master', 'officer'],
    navGroup: 'Roster & Workforce',
    navLabel: 'Open Shifts',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.availability',
    path: '/availability',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master', 'officer'],
    navGroup: 'Roster & Workforce',
    navLabel: 'My Availability',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.officer-skills',
    path: '/officer-skills',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Roster & Workforce',
    navLabel: 'Skills & Licences',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.timesheets',
    path: '/timesheets',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Roster & Workforce',
    navLabel: 'Timesheets',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.bob-assistant',
    path: '/bob-assistant',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master', 'officer'],
    navGroup: 'Bob',
    navLabel: 'Bob Assistant',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.bob-intake-queue',
    path: '/bob-intake-queue',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Bob',
    navLabel: 'Bob Intake Queue',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.live-plan-reviews',
    path: '/live-plan-reviews',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Bob',
    navLabel: 'Live Plan Reviews',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.spatial-compliance',
    path: '/spatial-compliance',
    shell: 'admin',
    rolesAllowed: ['admin', 'master', 'grand_master'],
    navGroup: 'Tools',
    navLabel: 'Spatial Compliance',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.compliance-recalculation',
    path: '/compliance-recalculation',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Tools',
    navLabel: 'Recalculation',
    visibilityMode: 'internal',
    featureFlag: 'enable_internal_tools',
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.cleanup-recalculate',
    path: '/admin/cleanup-recalculate',
    shell: 'admin',
    rolesAllowed: ['admin', 'master', 'grand_master'],
    navGroup: 'Tools',
    navLabel: 'Cleanup & Recalculate',
    visibilityMode: 'internal',
    featureFlag: 'enable_internal_tools',
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.data',
    path: '/data',
    shell: 'admin',
    rolesAllowed: ['admin', 'master', 'grand_master'],
    navGroup: 'Tools',
    navLabel: 'Data Management',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.data-hub',
    path: '/admin/data-hub',
    shell: 'admin',
    rolesAllowed: ['admin', 'master', 'grand_master'],
    navGroup: 'Tools',
    navLabel: 'Data Hub',
    visibilityMode: 'internal',
    featureFlag: 'enable_internal_tools',
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'master.intel-approvals',
    path: '/intel-approvals',
    shell: 'master',
    rolesAllowed: ['master', 'grand_master'],
    navGroup: 'Tools',
    navLabel: 'Intel Approvals',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.import-historical',
    path: '/import-historical',
    shell: 'admin',
    rolesAllowed: ['admin', 'master', 'grand_master'],
    navGroup: 'Tools',
    navLabel: 'Import Data',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.import-data',
    path: '/import-data',
    shell: 'admin',
    rolesAllowed: ['admin', 'master', 'grand_master'],
    navGroup: 'Tools',
    navLabel: 'Import Data',
    visibilityMode: 'hidden',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.photo-reingest',
    path: '/photo-reingest',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Tools',
    navLabel: 'Photo Reingest',
    visibilityMode: 'internal',
    featureFlag: 'enable_internal_tools',
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.evidence-photo-linker',
    path: '/evidence-photo-linker',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Tools',
    navLabel: 'Evidence Linker',
    visibilityMode: 'internal',
    featureFlag: 'enable_internal_tools',
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'master.diagnostics',
    path: '/diagnostics',
    shell: 'master',
    rolesAllowed: ['master', 'grand_master'],
    navGroup: 'Tools',
    navLabel: 'Diagnostics',
    visibilityMode: 'internal',
    featureFlag: 'enable_internal_tools',
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  {
    routeId: 'user.profile',
    path: '/profile',
    shell: 'shared',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master', 'officer'],
    navGroup: 'Settings',
    navLabel: 'My Profile',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'user.notifications',
    path: '/notifications',
    shell: 'shared',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master', 'officer'],
    navGroup: 'Settings',
    navLabel: 'Notifications',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'user.settings',
    path: '/settings',
    shell: 'shared',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master', 'officer', 'nzscv_monitor'],
    navGroup: 'Settings',
    navLabel: 'Settings',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'master.platform',
    path: '/platform',
    shell: 'master',
    rolesAllowed: ['grand_master'],
    navGroup: 'Platform',
    navLabel: 'Platform',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: null,
    preloadPolicy: 'intent',
  },
  {
    routeId: 'master.access-control',
    path: '/access-control',
    shell: 'master',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    permissionArea: 'users',
    navGroup: 'Platform',
    navLabel: 'Access Control',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.test-dashboard',
    path: '/test-dashboard',
    shell: 'admin',
    rolesAllowed: ['master', 'grand_master'],
    navGroup: 'Internal',
    navLabel: 'Test Dashboard',
    visibilityMode: 'internal',
    featureFlag: 'enable_internal_tools',
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  // --- Internal data-repair tools (not surfaced in production nav) ---
  {
    routeId: 'admin.data-cleanup',
    path: '/admin/data-cleanup',
    shell: 'admin',
    rolesAllowed: ['admin', 'master', 'grand_master'],
    navGroup: 'Tools',
    navLabel: 'Data Cleanup',
    visibilityMode: 'internal',
    featureFlag: 'enable_internal_tools',
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.data-integrity',
    path: '/admin/data-integrity',
    shell: 'admin',
    rolesAllowed: ['admin', 'master', 'grand_master'],
    navGroup: 'Tools',
    navLabel: 'Data Integrity',
    visibilityMode: 'internal',
    featureFlag: 'enable_internal_tools',
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  // --- Hidden: dev/prototype routes (accessible if you know the path, not in nav) ---
  {
    routeId: 'admin.clean-dashboard',
    path: '/clean-dashboard',
    shell: 'admin',
    rolesAllowed: ['admin', 'master', 'grand_master'],
    navGroup: null,
    navLabel: null,
    visibilityMode: 'hidden',
    featureFlag: null,
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  // --- Production but nav-unlisted specialist routes ---
  {
    routeId: 'admin.custom-reports',
    path: '/custom-reports',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Records',
    navLabel: 'Custom Reports',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'grandmaster.coding-studio',
    path: '/grandmaster-code-studio',
    shell: 'master',
    rolesAllowed: ['grand_master'],
    navGroup: 'Platform',
    navLabel: 'Coding Studio',
    visibilityMode: 'internal',
    featureFlag: 'enable_internal_tools',
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  {
    routeId: 'grandmaster.compliance-escalations',
    path: '/compliance-escalations',
    shell: 'master',
    rolesAllowed: ['grand_master'],
    navGroup: 'Platform',
    navLabel: 'Compliance Escalations',
    visibilityMode: 'internal',
    featureFlag: 'enable_internal_tools',
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  // --- Sprint 18: B-64/B-65/B-66 ---
  {
    routeId: 'admin.health-safety-reports',
    path: '/health-safety-reports',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master'],
    navGroup: 'Records',
    navLabel: 'Health & Safety Reports',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.welfare-checkins',
    path: '/welfare-checkins',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master'],
    navGroup: 'Operations',
    navLabel: 'Welfare Check-in Log',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.parking-permits',
    path: '/parking-permits',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master'],
    navGroup: 'Operations',
    navLabel: 'Parking Permits',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  // --- Sprint 19: B-67/B-68/B-69 ---
  {
    routeId: 'admin.roster-shifts',
    path: '/roster-shifts',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master'],
    navGroup: 'Roster & Workforce',
    navLabel: 'Roster Shift Log',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.noise-notices',
    path: '/noise-notices',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master'],
    navGroup: 'Operations',
    navLabel: 'Noise Notice Log',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.site-incidents',
    path: '/site-incidents',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master'],
    navGroup: 'Operations',
    navLabel: 'Site Incident Log',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  // --- Sprint 20: B-70/B-71/B-72 ---
  {
    routeId: 'admin.person-interactions',
    path: '/person-interactions',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master'],
    navGroup: 'Operations',
    navLabel: 'Person Interaction Log',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.plate-scans-log',
    path: '/plate-scans-log',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master'],
    navGroup: 'Management',
    navLabel: 'Plate Scan Log',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.dispatch-events',
    path: '/dispatch-events',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master'],
    navGroup: 'Live Ops',
    navLabel: 'Dispatch Event Log',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  // --- Sprint 21: B-73/B-74/B-75 ---
  {
    routeId: 'admin.notices-to-vacate',
    path: '/notices-to-vacate',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master'],
    navGroup: 'Operations',
    navLabel: 'Notice to Vacate Log',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.contractor-manager',
    path: '/contractor-manager',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master'],
    navGroup: 'Admin',
    navLabel: 'Contractor Manager',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.vehicle-discrepancies',
    path: '/vehicle-discrepancies',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master'],
    navGroup: 'Management',
    navLabel: 'Vehicle Discrepancy Log',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  // --- Sprint 22: B-76/B-77/B-78 ---
  {
    routeId: 'admin.drift-events',
    path: '/drift-events',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master'],
    navGroup: 'Management',
    navLabel: 'Drift Event Log',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.investigation-job-config',
    path: '/investigation-job-config',
    shell: 'admin',
    rolesAllowed: ['admin', 'master'],
    navGroup: 'Records',
    navLabel: 'Investigation Job Config',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.zone-legal-config',
    path: '/zone-legal-config',
    shell: 'admin',
    rolesAllowed: ['admin', 'master'],
    navGroup: 'Management',
    navLabel: 'Zone Legal Config',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: null,
    preloadPolicy: 'none',
  },
]
