export type AppShell = 'officer' | 'admin' | 'master' | 'shared'

export type AppRole =
  | 'master'
  | 'admin'
  | 'officer'
  | 'admin_officer'
  | 'nzscv_monitor'
  | 'grand_master'
  | 'client_viewer'

export type VisibilityMode = 'production' | 'internal' | 'hidden'

export type PreloadPolicy = 'none' | 'intent' | 'viewport' | 'eager'

export interface RouteManifestEntry {
  routeId: string
  path: string
  shell: AppShell
  rolesAllowed: AppRole[]
  permissionArea?: string | null
  navGroup?: string | null
  navLabel?: string | null
  visibilityMode: VisibilityMode
  featureFlag?: string | null
  mobilePriority?: number | null
  preloadPolicy: PreloadPolicy
}

export const ROUTE_MANIFEST_VERSION = '2026-04-23.v2'

// Phase 1 seed manifest: only high-traffic primary routes.
// All canonical routes are now active. Legacy aliases exist only as backward-compatibility redirects.
export const routeManifest: RouteManifestEntry[] = [
  {
    routeId: 'auth.login',
    path: '/login',
    shell: 'shared',
    rolesAllowed: ['master', 'admin', 'officer', 'admin_officer', 'nzscv_monitor', 'grand_master', 'client_viewer'],
    navGroup: null,
    navLabel: null,
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: null,
    preloadPolicy: 'eager',
  },
  {
    routeId: 'root.admin-hub',
    path: '/',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Core',
    navLabel: 'Admin Hub',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 1,
    preloadPolicy: 'intent',
  },
  {
    routeId: 'portal.selection',
    path: '/portal-selection',
    shell: 'shared',
    rolesAllowed: ['admin_officer'],
    navGroup: null,
    navLabel: null,
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  {
    routeId: 'officer.home',
    path: '/officer-home',
    shell: 'officer',
    rolesAllowed: ['officer', 'admin_officer'],
    navGroup: 'Officer',
    navLabel: 'Officer Home',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 1,
    preloadPolicy: 'intent',
  },
  {
    routeId: 'officer.field',
    path: '/field-officer',
    shell: 'officer',
    rolesAllowed: ['officer', 'admin_officer'],
    permissionArea: 'field_officer',
    navGroup: 'Officer',
    navLabel: 'Field Officer',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 1,
    preloadPolicy: 'intent',
  },
  {
    routeId: 'admin.dashboard',
    path: '/admin/dashboard',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Management',
    navLabel: 'Ops Dashboard',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'intent',
  },
  {
    routeId: 'admin.compliance',
    path: '/compliance',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Operations',
    navLabel: 'Compliance Hub',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'intent',
  },
  {
    routeId: 'admin.observation-records',
    path: '/observation-records',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master', 'officer'],
    navGroup: 'Operations',
    navLabel: 'Observations',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'intent',
  },
  {
    routeId: 'admin.observations-report',
    path: '/observations-report',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Operations',
    navLabel: 'Observations Report',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.breaches',
    path: '/breaches',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master', 'officer'],
    navGroup: 'Operations',
    navLabel: 'Breaches',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'intent',
  },
  {
    routeId: 'admin.breach-notices',
    path: '/breach-notices',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master', 'officer'],
    navGroup: 'Operations',
    navLabel: 'Breach Notices',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.enforcement-actions',
    path: '/enforcement-actions',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master', 'officer'],
    navGroup: 'Operations',
    navLabel: 'Enforcement Actions',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.enforcement-review',
    path: '/enforcement-review',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Operations',
    navLabel: 'Enforcement Review',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.enforcement-command-center',
    path: '/enforcement-command-center',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Operations',
    navLabel: 'Enforcement Console',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'intent',
  },
  {
    routeId: 'admin.disputes',
    path: '/disputes',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Operations',
    navLabel: 'Disputes',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.notice-to-vacate',
    path: '/notice-to-vacate',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Operations',
    navLabel: 'Notice to Vacate',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.discrepancies',
    path: '/admin/discrepancies',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Operations',
    navLabel: 'Discrepancies',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.infringements',
    path: '/infringements',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master', 'officer'],
    navGroup: 'Operations',
    navLabel: 'Infringements',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.compliance-analytics',
    path: '/compliance-analytics',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Operations',
    navLabel: 'Compliance Analytics',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.patrol-checkpoints',
    path: '/patrol-checkpoints',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Operations',
    navLabel: 'Checkpoints',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.patrol-schedule',
    path: '/patrol-schedule',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Operations',
    navLabel: 'Patrol Schedule',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.patrol-kpis',
    path: '/patrol-kpis',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Operations',
    navLabel: 'Patrol KPIs',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.vehicles',
    path: '/vehicles',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master', 'officer'],
    navGroup: 'Management',
    navLabel: 'Vehicles',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'intent',
  },
  {
    routeId: 'admin.vehicle-registry',
    path: '/vehicle-registry',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master', 'nzscv_monitor'],
    navGroup: 'Management',
    navLabel: 'Vehicle Registry',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'intent',
  },
  {
    routeId: 'admin.nzscv-monitor',
    path: '/admin/nzscv',
    shell: 'admin',
    rolesAllowed: ['admin', 'master', 'grand_master', 'nzscv_monitor'],
    navGroup: 'Management',
    navLabel: 'NZSCV Monitor',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.canonical-records',
    path: '/admin/canonical-records',
    shell: 'admin',
    rolesAllowed: ['admin', 'master', 'grand_master'],
    navGroup: 'Management',
    navLabel: 'Canonical Records',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.zones',
    path: '/zones',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Management',
    navLabel: 'Zones',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'intent',
  },
  {
    routeId: 'admin.client-master-list',
    path: '/client-master-list',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Management',
    navLabel: 'Client Master List',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.client-sites',
    path: '/client-sites',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Management',
    navLabel: 'Client Sites',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.site-permissions',
    path: '/site-permissions',
    shell: 'admin',
    rolesAllowed: ['admin', 'master', 'grand_master'],
    navGroup: 'Management',
    navLabel: 'Site Permissions',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.crm',
    path: '/crm',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Management',
    navLabel: 'CRM / Accounts',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.tender-workspace',
    path: '/tender-workspace',
    shell: 'admin',
    rolesAllowed: ['admin', 'master', 'grand_master'],
    navGroup: 'Management',
    navLabel: 'Tenders & Contracts',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.tender-reference-library',
    path: '/tender-reference-library',
    shell: 'admin',
    rolesAllowed: ['admin', 'master', 'grand_master'],
    navGroup: 'Management',
    navLabel: 'Reference Library',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.pricing',
    path: '/pricing',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Management',
    navLabel: 'Service Pricing',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.invoicing',
    path: '/invoicing',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Management',
    navLabel: 'Invoicing',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.users',
    path: '/users',
    shell: 'admin',
    rolesAllowed: ['admin', 'master', 'grand_master'],
    navGroup: 'Management',
    navLabel: 'Users',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.organization-profile',
    path: '/organization-profile',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Management',
    navLabel: 'Organisation',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'master.organizations',
    path: '/organizations',
    shell: 'master',
    rolesAllowed: ['master', 'grand_master'],
    navGroup: 'Management',
    navLabel: 'Organisations',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.hotspots',
    path: '/hotspots',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Live Ops',
    navLabel: 'Hotspots Map',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.reports',
    path: '/reports',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Records',
    navLabel: 'Reports',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'intent',
  },
  {
    routeId: 'admin.incidents',
    path: '/incidents',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master', 'officer'],
    navGroup: 'Records',
    navLabel: 'Incidents & Evidence',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'intent',
  },
  {
    routeId: 'admin.incident-reports',
    path: '/incident-reports',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Records',
    navLabel: 'Incident Reports',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.investigations',
    path: '/investigations',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Records',
    navLabel: 'Investigations',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.person-records',
    path: '/person-records',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Records',
    navLabel: 'Person Records',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.reports-hub',
    path: '/reports-hub',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Records',
    navLabel: 'Reports Hub',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'intent',
  },
  {
    routeId: 'admin.audit-log',
    path: '/audit-log',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Records',
    navLabel: 'Audit Log',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.privacy-curtain',
    path: '/privacy-curtain',
    shell: 'admin',
    rolesAllowed: ['admin', 'master', 'grand_master'],
    navGroup: 'Records',
    navLabel: 'Privacy Curtain',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.observations-map',
    path: '/observations',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Records',
    navLabel: 'Observation Map',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.ai-analysis',
    path: '/ai-analysis',
    shell: 'admin',
    rolesAllowed: ['admin', 'master', 'grand_master'],
    navGroup: 'Bob',
    navLabel: 'Bob Analysis',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.live-tracking',
    path: '/live-tracking',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Live Ops',
    navLabel: 'Live Tracking',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'intent',
  },
  {
    routeId: 'admin.live-patrol',
    path: '/live-patrol',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Live Ops',
    navLabel: 'Live Patrol Monitor',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'intent',
  },
  {
    routeId: 'admin.operations-map',
    path: '/operations-map',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Live Ops',
    navLabel: 'Operations Map',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.dispatch',
    path: '/dispatch',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Live Ops',
    navLabel: 'Dispatch Console',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.dispatch-monitor',
    path: '/dispatch-monitor',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Live Ops',
    navLabel: 'Dispatch Monitor',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.dispatch-wizard',
    path: '/dispatch-wizard',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Live Ops',
    navLabel: 'Dispatch Wizard',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.dispatched-jobs',
    path: '/dispatched-jobs',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Live Ops',
    navLabel: 'Dispatched Jobs',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.team-chat',
    path: '/team-chat',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master', 'officer'],
    navGroup: 'Live Ops',
    navLabel: 'Team Chat',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.radio',
    path: '/radio',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master', 'officer'],
    navGroup: 'Live Ops',
    navLabel: 'Radio',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.noise-control',
    path: '/noise-control',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Specialist Portals',
    navLabel: 'Noise Control',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.biosecurity-control',
    path: '/biosecurity-control',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Specialist Portals',
    navLabel: 'Biosecurity (CNG)',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.smoke-control',
    path: '/smoke-control',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Specialist Portals',
    navLabel: 'Smoke Complaints (OOH)',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.parking',
    path: '/parking',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Specialist Portals',
    navLabel: 'Parking Enforcement',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.officer-welfare',
    path: '/officer-welfare',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Specialist Portals',
    navLabel: 'Officer Welfare',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.identity-verification',
    path: '/identity-verification',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Specialist Portals',
    navLabel: 'ID Verification',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.parking-officer',
    path: '/parking-officer',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Specialist Services',
    navLabel: 'Parking Officer',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.noise-officer',
    path: '/noise-officer',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Specialist Services',
    navLabel: 'Noise Officer',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.compliance-dashboard',
    path: '/compliance-dashboard',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Compliance',
    navLabel: 'Compliance Dashboard',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 2,
    preloadPolicy: 'intent',
  },
  {
    routeId: 'admin.face-recognition',
    path: '/face-recognition',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'People & Incidents',
    navLabel: 'Face Recognition',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.points-of-interest',
    path: '/points-of-interest',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'People & Incidents',
    navLabel: 'Points of Interest',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.site-risk-assessment',
    path: '/site-risk-assessment',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'People & Incidents',
    navLabel: 'Site Risk Assessment',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.roster',
    path: '/roster',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Roster & Workforce',
    navLabel: 'Roster Planner',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.open-shifts',
    path: '/open-shifts',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master', 'officer'],
    navGroup: 'Roster & Workforce',
    navLabel: 'Open Shifts',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.availability',
    path: '/availability',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master', 'officer'],
    navGroup: 'Roster & Workforce',
    navLabel: 'My Availability',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.officer-skills',
    path: '/officer-skills',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Roster & Workforce',
    navLabel: 'Skills & Licences',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.timesheets',
    path: '/timesheets',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Roster & Workforce',
    navLabel: 'Timesheets',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.bob-assistant',
    path: '/bob-assistant',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master', 'officer'],
    navGroup: 'Bob',
    navLabel: 'Bob Assistant',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.bob-intake-queue',
    path: '/bob-intake-queue',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Bob',
    navLabel: 'Bob Intake Queue',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.live-plan-reviews',
    path: '/live-plan-reviews',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Bob',
    navLabel: 'Live Plan Reviews',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.spatial-compliance',
    path: '/spatial-compliance',
    shell: 'admin',
    rolesAllowed: ['admin', 'master', 'grand_master'],
    navGroup: 'Tools',
    navLabel: 'Spatial Compliance',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.compliance-recalculation',
    path: '/compliance-recalculation',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Tools',
    navLabel: 'Recalculation',
    visibilityMode: 'internal',
    featureFlag: 'enable_internal_tools',
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.cleanup-recalculate',
    path: '/admin/cleanup-recalculate',
    shell: 'admin',
    rolesAllowed: ['admin', 'master', 'grand_master'],
    navGroup: 'Tools',
    navLabel: 'Cleanup & Recalculate',
    visibilityMode: 'internal',
    featureFlag: 'enable_internal_tools',
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.data',
    path: '/data',
    shell: 'admin',
    rolesAllowed: ['admin', 'master', 'grand_master'],
    navGroup: 'Tools',
    navLabel: 'Data Management',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.data-hub',
    path: '/admin/data-hub',
    shell: 'admin',
    rolesAllowed: ['admin', 'master', 'grand_master'],
    navGroup: 'Tools',
    navLabel: 'Data Hub',
    visibilityMode: 'internal',
    featureFlag: 'enable_internal_tools',
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'grand_master.raw-data-browser',
    path: '/admin/raw-data-browser',
    shell: 'master',
    rolesAllowed: ['grand_master'],
    navGroup: 'Tools',
    navLabel: 'Raw Data Browser',
    visibilityMode: 'internal',
    featureFlag: null,
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  {
    routeId: 'master.intel-approvals',
    path: '/intel-approvals',
    shell: 'master',
    rolesAllowed: ['master', 'grand_master'],
    navGroup: 'Tools',
    navLabel: 'Intel Approvals',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.import-historical',
    path: '/import-historical',
    shell: 'admin',
    rolesAllowed: ['admin', 'master', 'grand_master'],
    navGroup: 'Tools',
    navLabel: 'Import Data',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.import-data',
    path: '/import-data',
    shell: 'admin',
    rolesAllowed: ['admin', 'master', 'grand_master'],
    navGroup: 'Tools',
    navLabel: 'Import Data',
    visibilityMode: 'hidden',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.photo-reingest',
    path: '/photo-reingest',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Tools',
    navLabel: 'Photo Reingest',
    visibilityMode: 'internal',
    featureFlag: 'enable_internal_tools',
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.evidence-photo-linker',
    path: '/evidence-photo-linker',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Tools',
    navLabel: 'Evidence Linker',
    visibilityMode: 'internal',
    featureFlag: 'enable_internal_tools',
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'master.diagnostics',
    path: '/diagnostics',
    shell: 'master',
    rolesAllowed: ['master', 'grand_master'],
    navGroup: 'Tools',
    navLabel: 'Diagnostics',
    visibilityMode: 'internal',
    featureFlag: 'enable_internal_tools',
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  {
    routeId: 'user.profile',
    path: '/profile',
    shell: 'shared',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master', 'officer'],
    navGroup: 'Settings',
    navLabel: 'My Profile',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'user.notifications',
    path: '/notifications',
    shell: 'shared',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master', 'officer'],
    navGroup: 'Settings',
    navLabel: 'Notifications',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'user.settings',
    path: '/settings',
    shell: 'shared',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master', 'officer', 'nzscv_monitor'],
    navGroup: 'Settings',
    navLabel: 'Settings',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'master.platform',
    path: '/platform',
    shell: 'master',
    rolesAllowed: ['grand_master'],
    navGroup: 'Platform',
    navLabel: 'Platform',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: null,
    preloadPolicy: 'intent',
  },
  {
    routeId: 'master.access-control',
    path: '/access-control',
    shell: 'master',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    permissionArea: 'users',
    navGroup: 'Platform',
    navLabel: 'Access Control',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.test-dashboard',
    path: '/test-dashboard',
    shell: 'admin',
    rolesAllowed: ['master', 'grand_master'],
    navGroup: 'Internal',
    navLabel: 'Test Dashboard',
    visibilityMode: 'internal',
    featureFlag: 'enable_internal_tools',
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  // --- Internal data-repair tools (not surfaced in production nav) ---
  {
    routeId: 'admin.data-cleanup',
    path: '/admin/data-cleanup',
    shell: 'admin',
    rolesAllowed: ['admin', 'master', 'grand_master'],
    navGroup: 'Tools',
    navLabel: 'Data Cleanup',
    visibilityMode: 'internal',
    featureFlag: 'enable_internal_tools',
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  {
    routeId: 'admin.data-integrity',
    path: '/admin/data-integrity',
    shell: 'admin',
    rolesAllowed: ['admin', 'master', 'grand_master'],
    navGroup: 'Tools',
    navLabel: 'Data Integrity',
    visibilityMode: 'internal',
    featureFlag: 'enable_internal_tools',
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  // --- Hidden: dev/prototype routes (accessible if you know the path, not in nav) ---
  {
    routeId: 'admin.clean-dashboard',
    path: '/clean-dashboard',
    shell: 'admin',
    rolesAllowed: ['admin', 'master', 'grand_master'],
    navGroup: null,
    navLabel: null,
    visibilityMode: 'hidden',
    featureFlag: null,
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  // --- Production but nav-unlisted specialist routes ---
  {
    routeId: 'admin.custom-reports',
    path: '/custom-reports',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'],
    navGroup: 'Records',
    navLabel: 'Custom Reports',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 3,
    preloadPolicy: 'none',
  },
  {
    routeId: 'grandmaster.coding-studio',
    path: '/grandmaster-code-studio',
    shell: 'master',
    rolesAllowed: ['grand_master'],
    navGroup: 'Platform',
    navLabel: 'Coding Studio',
    visibilityMode: 'internal',
    featureFlag: 'enable_internal_tools',
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  {
    routeId: 'grandmaster.compliance-escalations',
    path: '/compliance-escalations',
    shell: 'master',
    rolesAllowed: ['grand_master'],
    navGroup: 'Platform',
    navLabel: 'Compliance Escalations',
    visibilityMode: 'internal',
    featureFlag: 'enable_internal_tools',
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  // Sprint 14 — On-Call Rostering & Allowances
  // Sprint 14 — On-Call Rostering & Allowances
  {
    routeId: 'roster.on-call-periods',
    path: '/on-call-periods',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'officer'],
    permissionArea: 'roster',
    navGroup: 'Roster & Workforce',
    navLabel: 'On-Call Periods',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 4,
    preloadPolicy: 'none',
  },
  {
    routeId: 'roster.callout-shifts',
    path: '/callout-shifts',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master', 'officer'],
    permissionArea: 'roster',
    navGroup: 'Roster & Workforce',
    navLabel: 'Callout Shifts',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: 4,
    preloadPolicy: 'none',
  },
  {
    routeId: 'roster.officer-allowances',
    path: '/officer-allowances',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master'],
    permissionArea: 'roster',
    navGroup: 'Roster & Workforce',
    navLabel: 'Officer Allowances',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  {
    routeId: 'roster.travel-allowances',
    path: '/travel-allowances',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master'],
    permissionArea: 'roster',
    navGroup: 'Roster & Workforce',
    navLabel: 'Travel Allowances',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  {
    routeId: 'enforcement.parking-appeals',
    path: '/parking-appeals',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master'],
    permissionArea: 'enforcement',
    navGroup: 'Roster & Workforce',
    navLabel: 'Parking Appeals',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  {
    routeId: 'operations.camper-registrations',
    path: '/camper-registrations',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master'],
    permissionArea: 'operations',
    navGroup: 'Roster & Workforce',
    navLabel: 'Camper Registrations',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  {
    routeId: 'management.zone-amenities',
    path: '/zone-amenities',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master'],
    permissionArea: 'management',
    navGroup: 'Management',
    navLabel: 'Zone Amenities',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  {
    routeId: 'noise.noise-complaints',
    path: '/noise-complaints',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master'],
    permissionArea: 'noise',
    navGroup: 'Live Ops',
    navLabel: 'Noise Complaints Log',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  {
    routeId: 'patrols.patrol-events',
    path: '/patrol-events',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master'],
    permissionArea: 'patrols',
    navGroup: 'Patrols',
    navLabel: 'Patrol Event Log',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  {
    routeId: 'enforcement.breach-escalation',
    path: '/breach-escalation',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master'],
    permissionArea: 'enforcement',
    navGroup: 'Live Ops',
    navLabel: 'Breach Escalation',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  {
    routeId: 'patrols.officer-performance',
    path: '/officer-performance',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master'],
    permissionArea: 'patrols',
    navGroup: 'Patrols',
    navLabel: 'Officer Performance Report',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  {
    routeId: 'records.site-risk-trends',
    path: '/site-risk-trends',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master'],
    permissionArea: 'records',
    navGroup: 'Records',
    navLabel: 'Site Risk Trends',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  {
    routeId: 'enforcement.incident-heatmap',
    path: '/incident-heatmap',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master'],
    permissionArea: 'enforcement',
    navGroup: 'Live Ops',
    navLabel: 'Incident Heatmap',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  {
    routeId: 'operations.health-safety-reports',
    path: '/health-safety-reports',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master'],
    permissionArea: 'operations',
    navGroup: 'Operations',
    navLabel: 'Health & Safety Reports',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  {
    routeId: 'operations.welfare-checkins',
    path: '/welfare-checkins',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master'],
    permissionArea: 'operations',
    navGroup: 'Operations',
    navLabel: 'Welfare Check-in Log',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  {
    routeId: 'management.parking-permits',
    path: '/parking-permits',
    shell: 'admin',
    rolesAllowed: ['admin', 'admin_officer', 'master'],
    permissionArea: 'management',
    navGroup: 'Management',
    navLabel: 'Parking Permit Manager',
    visibilityMode: 'production',
    featureFlag: null,
    mobilePriority: null,
    preloadPolicy: 'none',
  },
  // --- Sprint 22–26: B-76–B-90 ---
  { routeId: 'admin.roster-shifts', path: '/roster-shifts', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Roster & Workforce', navLabel: 'Roster Shift Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.noise-notices', path: '/noise-notices', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Noise Notices', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.site-incidents', path: '/site-incidents', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Site Incidents', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.person-interactions', path: '/person-interactions', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Person Interactions', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.plate-scans-log', path: '/plate-scans-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Plate Scans', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.dispatch-events', path: '/dispatch-events', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Dispatch Events', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.notices-to-vacate', path: '/notices-to-vacate', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Notices to Vacate', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.contractor-manager', path: '/contractor-manager', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Roster & Workforce', navLabel: 'Contractor Manager', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.vehicle-discrepancies', path: '/vehicle-discrepancies', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Vehicle Discrepancies', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.drift-events', path: '/drift-events', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Drift Events', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.investigation-job-config', path: '/investigation-job-config', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Management', navLabel: 'Investigation Job Config', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.zone-legal-config', path: '/zone-legal-config', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Management', navLabel: 'Zone Legal Config', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.investigation-jobs-log', path: '/investigation-jobs-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Investigation Jobs', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.operational-cases-log', path: '/operational-cases-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Operational Cases', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.patrol-events-log', path: '/patrol-events-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Patrol Events Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.checkpoint-visits-log', path: '/checkpoint-visits-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Checkpoint Visits', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.ems-attendances-log', path: '/ems-attendances-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'EMS Attendances', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.parking-sessions-log', path: '/parking-sessions-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Parking Sessions', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.flagged-vehicles-manager', path: '/flagged-vehicles-manager', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Management', navLabel: 'Flagged Vehicles', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.parking-payments-log', path: '/parking-payments-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Parking Payments', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.zone-signage-evidence', path: '/zone-signage-evidence', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Zone Signage Evidence', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.officer-activity-log', path: '/officer-activity-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Officer Activity Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.credential-processing-log', path: '/credential-processing-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Credential Processing', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.dispatch-ack-log', path: '/dispatch-ack-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Dispatch Acknowledgements', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  // --- Sprint 27: B-91–B-93 ---
  { routeId: 'admin.compliance-audit-log', path: '/compliance-audit-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Compliance', navLabel: 'Compliance Audit Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.enforcement-events-log', path: '/enforcement-events-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Enforcement', navLabel: 'Enforcement Event Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.noise-jobs-log', path: '/noise-jobs-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Noise Job Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  // --- Sprint 28: B-94–B-96 ---
  { routeId: 'admin.patrol-route-log', path: '/patrol-route-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Operations', navLabel: 'Patrol Route Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.alarm-events-log', path: '/alarm-events-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Operations', navLabel: 'Alarm Event Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.bug-reports-log', path: '/bug-reports-log', shell: 'admin', rolesAllowed: ['admin', 'master'], navGroup: 'Management', navLabel: 'Bug Report Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  // --- Sprint 29: B-97–B-99 ---
  { routeId: 'admin.radio-transmissions-log', path: '/radio-transmissions-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master', 'officer'], navGroup: 'Operations', navLabel: 'Radio Transmission Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.noise-assessments-log', path: '/noise-assessments-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Noise Assessment Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  // --- Sprint 30: B-100–B-102 ---
  { routeId: 'admin.trespass-notices-log', path: '/trespass-notices-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Enforcement', navLabel: 'Trespass Notice Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.parking-infringements-log', path: '/parking-infringements-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Enforcement', navLabel: 'Parking Infringement Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.person-observations-log', path: '/person-observations-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Person Observation Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  // --- Sprint 31: B-103–B-105 ---
  { routeId: 'admin.vehicles-of-interest-log', path: '/vehicles-of-interest-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Enforcement', navLabel: 'Vehicles of Interest Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.persons-of-interest-log', path: '/persons-of-interest-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Enforcement', navLabel: 'Persons of Interest Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.photo-metadata-log', path: '/photo-metadata-log', shell: 'admin', rolesAllowed: ['admin', 'master'], navGroup: 'Records', navLabel: 'Photo Metadata Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  // --- Sprint 32: B-106–B-108 ---
  { routeId: 'admin.radio-comms-events-log', path: '/radio-comms-events-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Operations', navLabel: 'Radio Comms Event Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.case-comments-log', path: '/case-comments-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Case Comment Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.lmr-bridge-sessions-log', path: '/lmr-bridge-sessions-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Operations', navLabel: 'LMR Bridge Session Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  // --- Sprint 33: B-109–B-111 ---
  { routeId: 'admin.patrol-session-events-log', path: '/patrol-session-events-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Operations', navLabel: 'Patrol Session Events', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.radio-transcript-log', path: '/radio-transcript-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Operations', navLabel: 'Radio Transcript Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.dispute-intake-log', path: '/dispute-intake-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Dispute Intake Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  // --- Sprint 34: B-112–B-114 ---
  { routeId: 'admin.radio-tts-render-log', path: '/radio-tts-render-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Operations', navLabel: 'Radio TTS Render Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.health-safety-report-log', path: '/health-safety-report-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Health Safety Report Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.noise-seizures-log', path: '/noise-seizures-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Enforcement', navLabel: 'Noise Seizure Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  // --- Sprint 35: B-115–B-117 ---
  { routeId: 'admin.locations-of-interest-log', path: '/locations-of-interest-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Locations of Interest Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.vehicle-monthly-stays-log', path: '/vehicle-monthly-stays-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Vehicle Monthly Stays Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.radio-voice-consent-log', path: '/radio-voice-consent-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Operations', navLabel: 'Radio Voice Consent Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  // --- Sprint 36: B-118–B-120 ---
  { routeId: 'admin.patrol-field-events-log', path: '/patrol-field-events-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Operations', navLabel: 'Patrol Field Event Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.alert-queue-log', path: '/alert-queue-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Operations', navLabel: 'Alert Queue Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.compliance-results-log', path: '/compliance-results-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Enforcement', navLabel: 'Compliance Result Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  // --- Sprint 37: B-121–B-123 ---
  { routeId: 'admin.welfare-events-log', path: '/welfare-events-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Welfare Events Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.zone-geofence-snapshots', path: '/zone-geofence-snapshots', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Management', navLabel: 'Zone Geofence Snapshots', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.feature-flags', path: '/feature-flags', shell: 'admin', rolesAllowed: ['master'], navGroup: 'Management', navLabel: 'Feature Flags', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  // --- Sprint 38: B-124–B-126 ---
  { routeId: 'admin.feature-flag-evaluations-log', path: '/feature-flag-evaluations-log', shell: 'admin', rolesAllowed: ['master'], navGroup: 'Management', navLabel: 'Flag Evaluation Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.feature-flag-rollout-log', path: '/feature-flag-rollout-log', shell: 'admin', rolesAllowed: ['master'], navGroup: 'Management', navLabel: 'Flag Rollout Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.missing-photo-queue', path: '/missing-photo-queue', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Missing Photo Queue', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  // --- Sprint 39: B-127–B-129 ---
  { routeId: 'admin.photo-integrity-health-log', path: '/photo-integrity-health-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Photo Integrity Health', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.photo-recovery-audit-log', path: '/photo-recovery-audit-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Photo Recovery Audit Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.user-sessions-log', path: '/user-sessions-log', shell: 'admin', rolesAllowed: ['master'], navGroup: 'Management', navLabel: 'User Sessions Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  // --- Sprint 40: B-130–B-132 ---
  { routeId: 'admin.recent-observations-photo-status-log', path: '/recent-observations-photo-status-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Recent Observation Photo Status', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.observation-zone-audit-log', path: '/observation-zone-audit-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Management', navLabel: 'Observation Zone Audit Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.user-deactivation-queue-log', path: '/user-deactivation-queue-log', shell: 'admin', rolesAllowed: ['master'], navGroup: 'Management', navLabel: 'User Deactivation Queue Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  // --- Sprint 41: B-133–B-135 ---
  { routeId: 'admin.alert-acknowledgements-log', path: '/alert-acknowledgements-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Operations', navLabel: 'Alert Acknowledgements Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.officer-welfare-alerts-log', path: '/officer-welfare-alerts-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Operations', navLabel: 'Officer Welfare Alerts Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.vehicle-migration-log', path: '/vehicle-migration-log', shell: 'admin', rolesAllowed: ['master'], navGroup: 'Management', navLabel: 'Vehicle Migration Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  // --- Sprint 42: B-136–B-138 ---
  { routeId: 'admin.observation-deletions-log', path: '/observation-deletions-log', shell: 'admin', rolesAllowed: ['admin', 'master'], navGroup: 'Records', navLabel: 'Observation Deletion Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.dispatch-resources-log', path: '/dispatch-resources-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Operations', navLabel: 'Dispatch Resources Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.radio-translation-log', path: '/radio-translation-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Operations', navLabel: 'Radio Translation Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  // --- Sprint 43: B-139–B-141 ---
  { routeId: 'admin.bob-proposals-log', path: '/bob-proposals-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Bob', navLabel: 'Bob Proposal Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.bob-proposal-events-log', path: '/bob-proposal-events-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Bob', navLabel: 'Bob Proposal Event Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.import-batches-log', path: '/import-batches-log', shell: 'admin', rolesAllowed: ['admin', 'master'], navGroup: 'Management', navLabel: 'Import Batch Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  // --- Sprint 44: B-142–B-144 ---
  { routeId: 'admin.admin-recalculation-log', path: '/admin-recalculation-log', shell: 'admin', rolesAllowed: ['admin', 'master'], navGroup: 'Management', navLabel: 'Recalculation Run Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.contractor-documents-log', path: '/contractor-documents-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Contractor Document Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.import-staging-log', path: '/import-staging-log', shell: 'admin', rolesAllowed: ['admin', 'master'], navGroup: 'Management', navLabel: 'Import Staging Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  // --- Sprint 45: B-145–B-147 ---
  { routeId: 'admin.lmr-bridge-config-log', path: '/lmr-bridge-config-log', shell: 'admin', rolesAllowed: ['admin', 'master'], navGroup: 'Management', navLabel: 'LMR Bridge Config Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.radio-voice-profiles-log', path: '/radio-voice-profiles-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Operations', navLabel: 'Radio Voice Profile Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.zone-dispatch-rules-log', path: '/zone-dispatch-rules-log', shell: 'admin', rolesAllowed: ['admin', 'master'], navGroup: 'Management', navLabel: 'Zone Dispatch Rule Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  // --- Sprint 46: B-148–B-150 ---
  { routeId: 'admin.bob-action-proposal-events-log', path: '/bob-action-proposal-events-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Bob', navLabel: 'Bob Action Proposal Event Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.homeless-records-log', path: '/homeless-records-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Homeless Record Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.restrictions-log', path: '/restrictions-log', shell: 'admin', rolesAllowed: ['admin', 'master'], navGroup: 'Management', navLabel: 'Restriction Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  // --- Sprint 47: B-151–B-153 ---
  { routeId: 'admin.organizations-log', path: '/organizations-log', shell: 'admin', rolesAllowed: ['master', 'grand_master'], navGroup: 'Management', navLabel: 'Organization Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.client-sites-log', path: '/client-sites-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Client Site Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.parking-permits-log', path: '/parking-permits-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Specialist Portals', navLabel: 'Parking Permit Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  // --- Sprint 48: B-154–B-156 ---
  { routeId: 'admin.incidents-log', path: '/incidents-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Operations', navLabel: 'Incident Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.person-records-log', path: '/person-records-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Person Record Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.notifications-log', path: '/notifications-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Operations', navLabel: 'Notification Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  // --- Sprint 49: B-157–B-159 ---
  { routeId: 'admin.face-records-log', path: '/face-records-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Face Record Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.infringement-notices-log', path: '/infringement-notices-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Operations', navLabel: 'Infringement Notice Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.site-risk-assessments-log', path: '/site-risk-assessments-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Site Risk Assessment Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  // --- Sprint 50: B-160–B-162 ---
  { routeId: 'admin.dispatch-jobs-log', path: '/dispatch-jobs-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Operations', navLabel: 'Dispatch Job Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.enforcement-actions-log', path: '/enforcement-actions-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Operations', navLabel: 'Enforcement Action Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.observations-log', path: '/observations-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Observation Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  // --- Sprint 51: B-163–B-165 ---
  { routeId: 'admin.canonical-scv-log', path: '/canonical-scv-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Canonical SCV Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.officer-availability-log', path: '/officer-availability-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Operations', navLabel: 'Officer Availability Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.canonical-homeless-log', path: '/canonical-homeless-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Canonical Homeless Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  // --- Sprint 52: B-166–B-168 ---
  { routeId: 'admin.breach-alerts-log', path: '/breach-alerts-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Operations', navLabel: 'Breach Alert Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.canonical-vehicles-log', path: '/canonical-vehicles-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Canonical Vehicle Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.flagged-vehicles-log', path: '/flagged-vehicles-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Operations', navLabel: 'Flagged Vehicle Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  // --- Sprint 53: B-169–B-171 ---
  { routeId: 'admin.officer-shifts-log', path: '/officer-shifts-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Operations', navLabel: 'Officer Shift Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.open-shifts-log', path: '/open-shifts-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Operations', navLabel: 'Open Shift Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.zone-compliance-matrix-log', path: '/zone-compliance-matrix-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Management', navLabel: 'Zone Compliance Matrix Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  // --- Sprint 54: B-172–B-174 ---
  { routeId: 'admin.pricing-rules-log', path: '/pricing-rules-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Operations', navLabel: 'Pricing Rule Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.zone-legal-config-log', path: '/zone-legal-config-log', shell: 'admin', rolesAllowed: ['admin', 'master'], navGroup: 'Management', navLabel: 'Zone Legal Config Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.zone-signage-evidence-log', path: '/zone-signage-evidence-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Zone Signage Evidence Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  // --- Sprint 55: B-175–B-177 ---
  { routeId: 'admin.fixed-cameras-log', path: '/fixed-cameras-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Operations', navLabel: 'Fixed Camera Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.officer-skills-log', path: '/officer-skills-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Operations', navLabel: 'Officer Skills Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.patrol-checkpoints-log', path: '/patrol-checkpoints-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Operations', navLabel: 'Patrol Checkpoint Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  // --- Sprint 56: B-178–B-180 ---
  { routeId: 'admin.contractor-profiles-log', path: '/contractor-profiles-log', shell: 'admin', rolesAllowed: ['admin', 'master'], navGroup: 'Records', navLabel: 'Contractor Profile Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.parking-zones-log', path: '/parking-zones-log', shell: 'admin', rolesAllowed: ['admin', 'master'], navGroup: 'Management', navLabel: 'Parking Zone Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.canonical-persons-log', path: '/canonical-persons-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Canonical Persons Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  // --- Sprint 57: B-181–B-183 ---
  { routeId: 'admin.alarm-events-log', path: '/alarm-events-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Operations', navLabel: 'Alarm Event Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.checkpoint-visits-log', path: '/checkpoint-visits-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Operations', navLabel: 'Checkpoint Visit Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.credential-processing-log', path: '/credential-processing-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Credential Processing Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  // --- Sprint 58: B-184–B-186 ---
  { routeId: 'admin.dispatch-ack-log', path: '/dispatch-ack-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Operations', navLabel: 'Dispatch Ack Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.drift-events', path: '/drift-events', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Operations', navLabel: 'Drift Events', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.ems-attendances-log', path: '/ems-attendances-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Operations', navLabel: 'EMS Attendance Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  // --- Sprint 59: B-187–B-189 ---
  { routeId: 'admin.enforcement-events-log', path: '/enforcement-events-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Enforcement', navLabel: 'Enforcement Event Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.health-safety-report-log', path: '/health-safety-report-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Records', navLabel: 'Health & Safety Report Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.officer-activity-log', path: '/officer-activity-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Operations', navLabel: 'Officer Activity Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  // --- Sprint 60: B-190–B-192 ---
  { routeId: 'admin.parking-payments-log', path: '/parking-payments-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Operations', navLabel: 'Parking Payment Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.parking-sessions-log', path: '/parking-sessions-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Operations', navLabel: 'Parking Session Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.plate-scans-log', path: '/plate-scans-log', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Operations', navLabel: 'Plate Scan Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  // --- Sprint 61: B-193–B-194 ---
  { routeId: 'admin.roster-shifts', path: '/roster-shifts', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Roster & Workforce', navLabel: 'Roster Shift Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  { routeId: 'admin.access-audit', path: '/access-audit', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master', 'grand_master'], navGroup: 'Records', navLabel: 'Access Audit Log', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
  // --- Briefing video suite ---
  { routeId: 'admin.video-generation-suite', path: '/admin/video-generation', shell: 'admin', rolesAllowed: ['admin', 'admin_officer', 'master'], navGroup: 'Bob', navLabel: 'Video Generation Suite', visibilityMode: 'production', featureFlag: null, mobilePriority: null, preloadPolicy: 'none' },
]
