-- Addendum to tender_documents: generation tracking columns
-- Stores which AI model/provider generated each draft section set,
-- enabling the frontend to show "Generated by Ollama (llama3.1:8b)" etc.

ALTER TABLE public.tender_documents
  ADD COLUMN IF NOT EXISTS assessment       JSONB,           -- alias for bob_assessment (edge fn compat)
  ADD COLUMN IF NOT EXISTS draft_sections   JSONB,           -- sections from generate-tender-sections (cover_letter, exec_summary, etc.)
  ADD COLUMN IF NOT EXISTS generation_type  TEXT             -- 'application' | 'response'
                                              CHECK (generation_type IN ('application', 'response')),
  ADD COLUMN IF NOT EXISTS generation_provider TEXT,         -- 'ollama' | 'ollama-writing' | 'secondary-assistant' | 'heuristic'
  ADD COLUMN IF NOT EXISTS generation_model TEXT,            -- e.g. 'llama3.1:8b', 'qwen2.5:14b', 'template'
  ADD COLUMN IF NOT EXISTS last_generated_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_generated_by UUID REFERENCES public.user_profiles(id);

-- Backfill assessment = bob_assessment for existing rows
UPDATE public.tender_documents SET assessment = bob_assessment WHERE assessment IS NULL AND bob_assessment IS NOT NULL;
